/**
 * Neomed Auth API
 * Neomed Auth API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EntityPermission', 'model/EntityRole', 'model/EntityUser', 'model/PresenterAuthToken', 'model/PresenterByPassFirebaseResponse', 'model/PresenterConfirmLoginByMobile', 'model/PresenterConfirmSignUpRequest', 'model/PresenterCreateDistributorAdminRequest', 'model/PresenterCreateDistributorUserRequest', 'model/PresenterCreateSuperAdminRequest', 'model/PresenterIdentityRequest', 'model/PresenterListProductsResponse', 'model/PresenterLoginByFirebaseRequest', 'model/PresenterLoginByMobileRequest', 'model/PresenterLoginByMobileResponse', 'model/PresenterPermission', 'model/PresenterRole', 'model/PresenterSignUpRequest', 'model/PresenterSignUpResponse', 'model/PresenterUpdatePassword', 'model/PresenterUpdateUserProfileRequest', 'model/PresenterUpdateUserRequest', 'model/Success', 'api/AuditlogsApi', 'api/AuthApi', 'api/RolesApi', 'api/UsersApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/EntityPermission'), require('./model/EntityRole'), require('./model/EntityUser'), require('./model/PresenterAuthToken'), require('./model/PresenterByPassFirebaseResponse'), require('./model/PresenterConfirmLoginByMobile'), require('./model/PresenterConfirmSignUpRequest'), require('./model/PresenterCreateDistributorAdminRequest'), require('./model/PresenterCreateDistributorUserRequest'), require('./model/PresenterCreateSuperAdminRequest'), require('./model/PresenterIdentityRequest'), require('./model/PresenterListProductsResponse'), require('./model/PresenterLoginByFirebaseRequest'), require('./model/PresenterLoginByMobileRequest'), require('./model/PresenterLoginByMobileResponse'), require('./model/PresenterPermission'), require('./model/PresenterRole'), require('./model/PresenterSignUpRequest'), require('./model/PresenterSignUpResponse'), require('./model/PresenterUpdatePassword'), require('./model/PresenterUpdateUserProfileRequest'), require('./model/PresenterUpdateUserRequest'), require('./model/Success'), require('./api/AuditlogsApi'), require('./api/AuthApi'), require('./api/RolesApi'), require('./api/UsersApi'));
  }
}(function(ApiClient, EntityPermission, EntityRole, EntityUser, PresenterAuthToken, PresenterByPassFirebaseResponse, PresenterConfirmLoginByMobile, PresenterConfirmSignUpRequest, PresenterCreateDistributorAdminRequest, PresenterCreateDistributorUserRequest, PresenterCreateSuperAdminRequest, PresenterIdentityRequest, PresenterListProductsResponse, PresenterLoginByFirebaseRequest, PresenterLoginByMobileRequest, PresenterLoginByMobileResponse, PresenterPermission, PresenterRole, PresenterSignUpRequest, PresenterSignUpResponse, PresenterUpdatePassword, PresenterUpdateUserProfileRequest, PresenterUpdateUserRequest, Success, AuditlogsApi, AuthApi, RolesApi, UsersApi) {
  'use strict';

  /**
   * Neomed_Auth_API.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var NeomedAuthApi = require('index'); // See note below*.
   * var xxxSvc = new NeomedAuthApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new NeomedAuthApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new NeomedAuthApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new NeomedAuthApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The EntityPermission model constructor.
     * @property {module:model/EntityPermission}
     */
    EntityPermission: EntityPermission,
    /**
     * The EntityRole model constructor.
     * @property {module:model/EntityRole}
     */
    EntityRole: EntityRole,
    /**
     * The EntityUser model constructor.
     * @property {module:model/EntityUser}
     */
    EntityUser: EntityUser,
    /**
     * The PresenterAuthToken model constructor.
     * @property {module:model/PresenterAuthToken}
     */
    PresenterAuthToken: PresenterAuthToken,
    /**
     * The PresenterByPassFirebaseResponse model constructor.
     * @property {module:model/PresenterByPassFirebaseResponse}
     */
    PresenterByPassFirebaseResponse: PresenterByPassFirebaseResponse,
    /**
     * The PresenterConfirmLoginByMobile model constructor.
     * @property {module:model/PresenterConfirmLoginByMobile}
     */
    PresenterConfirmLoginByMobile: PresenterConfirmLoginByMobile,
    /**
     * The PresenterConfirmSignUpRequest model constructor.
     * @property {module:model/PresenterConfirmSignUpRequest}
     */
    PresenterConfirmSignUpRequest: PresenterConfirmSignUpRequest,
    /**
     * The PresenterCreateDistributorAdminRequest model constructor.
     * @property {module:model/PresenterCreateDistributorAdminRequest}
     */
    PresenterCreateDistributorAdminRequest: PresenterCreateDistributorAdminRequest,
    /**
     * The PresenterCreateDistributorUserRequest model constructor.
     * @property {module:model/PresenterCreateDistributorUserRequest}
     */
    PresenterCreateDistributorUserRequest: PresenterCreateDistributorUserRequest,
    /**
     * The PresenterCreateSuperAdminRequest model constructor.
     * @property {module:model/PresenterCreateSuperAdminRequest}
     */
    PresenterCreateSuperAdminRequest: PresenterCreateSuperAdminRequest,
    /**
     * The PresenterIdentityRequest model constructor.
     * @property {module:model/PresenterIdentityRequest}
     */
    PresenterIdentityRequest: PresenterIdentityRequest,
    /**
     * The PresenterListProductsResponse model constructor.
     * @property {module:model/PresenterListProductsResponse}
     */
    PresenterListProductsResponse: PresenterListProductsResponse,
    /**
     * The PresenterLoginByFirebaseRequest model constructor.
     * @property {module:model/PresenterLoginByFirebaseRequest}
     */
    PresenterLoginByFirebaseRequest: PresenterLoginByFirebaseRequest,
    /**
     * The PresenterLoginByMobileRequest model constructor.
     * @property {module:model/PresenterLoginByMobileRequest}
     */
    PresenterLoginByMobileRequest: PresenterLoginByMobileRequest,
    /**
     * The PresenterLoginByMobileResponse model constructor.
     * @property {module:model/PresenterLoginByMobileResponse}
     */
    PresenterLoginByMobileResponse: PresenterLoginByMobileResponse,
    /**
     * The PresenterPermission model constructor.
     * @property {module:model/PresenterPermission}
     */
    PresenterPermission: PresenterPermission,
    /**
     * The PresenterRole model constructor.
     * @property {module:model/PresenterRole}
     */
    PresenterRole: PresenterRole,
    /**
     * The PresenterSignUpRequest model constructor.
     * @property {module:model/PresenterSignUpRequest}
     */
    PresenterSignUpRequest: PresenterSignUpRequest,
    /**
     * The PresenterSignUpResponse model constructor.
     * @property {module:model/PresenterSignUpResponse}
     */
    PresenterSignUpResponse: PresenterSignUpResponse,
    /**
     * The PresenterUpdatePassword model constructor.
     * @property {module:model/PresenterUpdatePassword}
     */
    PresenterUpdatePassword: PresenterUpdatePassword,
    /**
     * The PresenterUpdateUserProfileRequest model constructor.
     * @property {module:model/PresenterUpdateUserProfileRequest}
     */
    PresenterUpdateUserProfileRequest: PresenterUpdateUserProfileRequest,
    /**
     * The PresenterUpdateUserRequest model constructor.
     * @property {module:model/PresenterUpdateUserRequest}
     */
    PresenterUpdateUserRequest: PresenterUpdateUserRequest,
    /**
     * The Success model constructor.
     * @property {module:model/Success}
     */
    Success: Success,
    /**
     * The AuditlogsApi service constructor.
     * @property {module:api/AuditlogsApi}
     */
    AuditlogsApi: AuditlogsApi,
    /**
     * The AuthApi service constructor.
     * @property {module:api/AuthApi}
     */
    AuthApi: AuthApi,
    /**
     * The RolesApi service constructor.
     * @property {module:api/RolesApi}
     */
    RolesApi: RolesApi,
    /**
     * The UsersApi service constructor.
     * @property {module:api/UsersApi}
     */
    UsersApi: UsersApi
  };

  return exports;
}));
