/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterVersionRequest = factory(root.NeomedApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PresenterVersionRequest model module.
   * @module model/PresenterVersionRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterVersionRequest</code>.
   * @alias module:model/PresenterVersionRequest
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>PresenterVersionRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterVersionRequest} obj Optional instance to populate.
   * @return {module:model/PresenterVersionRequest} The populated <code>PresenterVersionRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('force_version')) {
        obj['force_version'] = ApiClient.convertToType(data['force_version'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('min_version')) {
        obj['min_version'] = ApiClient.convertToType(data['min_version'], 'String');
      }
      if (data.hasOwnProperty('os')) {
        obj['os'] = ApiClient.convertToType(data['os'], 'String');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
      }
      if (data.hasOwnProperty('version_lastest')) {
        obj['version_lastest'] = ApiClient.convertToType(data['version_lastest'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {String} force_version
   */
  exports.prototype['force_version'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} min_version
   */
  exports.prototype['min_version'] = undefined;
  /**
   * @member {String} os
   */
  exports.prototype['os'] = undefined;
  /**
   * @member {String} updated_at
   */
  exports.prototype['updated_at'] = undefined;
  /**
   * @member {String} version_lastest
   */
  exports.prototype['version_lastest'] = undefined;



  return exports;
}));


