/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterAccreditRequest = factory(root.NeomedApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PresenterAccreditRequest model module.
   * @module model/PresenterAccreditRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterAccreditRequest</code>.
   * @alias module:model/PresenterAccreditRequest
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>PresenterAccreditRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterAccreditRequest} obj Optional instance to populate.
   * @return {module:model/PresenterAccreditRequest} The populated <code>PresenterAccreditRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('add_distributors')) {
        obj['add_distributors'] = ApiClient.convertToType(data['add_distributors'], ['Number']);
      }
      if (data.hasOwnProperty('pharmacy_id')) {
        obj['pharmacy_id'] = ApiClient.convertToType(data['pharmacy_id'], 'Number');
      }
      if (data.hasOwnProperty('remove_distributors')) {
        obj['remove_distributors'] = ApiClient.convertToType(data['remove_distributors'], ['Number']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<Number>} add_distributors
   */
  exports.prototype['add_distributors'] = undefined;
  /**
   * @member {Number} pharmacy_id
   */
  exports.prototype['pharmacy_id'] = undefined;
  /**
   * @member {Array.<Number>} remove_distributors
   */
  exports.prototype['remove_distributors'] = undefined;



  return exports;
}));


