/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterPagination', 'model/PresenterRevenueData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterPagination'), require('./PresenterRevenueData'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterStatisticRevenueResponse = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterPagination, root.NeomedApi.PresenterRevenueData);
  }
}(this, function(ApiClient, PresenterPagination, PresenterRevenueData) {
  'use strict';




  /**
   * The PresenterStatisticRevenueResponse model module.
   * @module model/PresenterStatisticRevenueResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterStatisticRevenueResponse</code>.
   * @alias module:model/PresenterStatisticRevenueResponse
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>PresenterStatisticRevenueResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterStatisticRevenueResponse} obj Optional instance to populate.
   * @return {module:model/PresenterStatisticRevenueResponse} The populated <code>PresenterStatisticRevenueResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [PresenterRevenueData]);
      }
      if (data.hasOwnProperty('pagination')) {
        obj['pagination'] = PresenterPagination.constructFromObject(data['pagination']);
      }
      if (data.hasOwnProperty('total_income')) {
        obj['total_income'] = ApiClient.convertToType(data['total_income'], 'Number');
      }
      if (data.hasOwnProperty('total_net_income')) {
        obj['total_net_income'] = ApiClient.convertToType(data['total_net_income'], 'Number');
      }
      if (data.hasOwnProperty('total_tx')) {
        obj['total_tx'] = ApiClient.convertToType(data['total_tx'], 'Number');
      }
      if (data.hasOwnProperty('total_users')) {
        obj['total_users'] = ApiClient.convertToType(data['total_users'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/PresenterRevenueData>} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {module:model/PresenterPagination} pagination
   */
  exports.prototype['pagination'] = undefined;
  /**
   * @member {Number} total_income
   */
  exports.prototype['total_income'] = undefined;
  /**
   * @member {Number} total_net_income
   */
  exports.prototype['total_net_income'] = undefined;
  /**
   * @member {Number} total_tx
   */
  exports.prototype['total_tx'] = undefined;
  /**
   * @member {Number} total_users
   */
  exports.prototype['total_users'] = undefined;



  return exports;
}));


