/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterCreateBannerUpdateRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterCreateBannerUpdateRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterBannerMultiRequest = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterCreateBannerUpdateRequest);
  }
}(this, function(ApiClient, PresenterCreateBannerUpdateRequest) {
  'use strict';




  /**
   * The PresenterBannerMultiRequest model module.
   * @module model/PresenterBannerMultiRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterBannerMultiRequest</code>.
   * @alias module:model/PresenterBannerMultiRequest
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>PresenterBannerMultiRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterBannerMultiRequest} obj Optional instance to populate.
   * @return {module:model/PresenterBannerMultiRequest} The populated <code>PresenterBannerMultiRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('banners')) {
        obj['banners'] = ApiClient.convertToType(data['banners'], [PresenterCreateBannerUpdateRequest]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/PresenterCreateBannerUpdateRequest>} banners
   */
  exports.prototype['banners'] = undefined;



  return exports;
}));


