/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterAdsBannerStatus'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterAdsBannerStatus'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterAdsBanner = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterAdsBannerStatus);
  }
}(this, function(ApiClient, PresenterAdsBannerStatus) {
  'use strict';




  /**
   * The PresenterAdsBanner model module.
   * @module model/PresenterAdsBanner
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterAdsBanner</code>.
   * @alias module:model/PresenterAdsBanner
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>PresenterAdsBanner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterAdsBanner} obj Optional instance to populate.
   * @return {module:model/PresenterAdsBanner} The populated <code>PresenterAdsBanner</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('create_at')) {
        obj['create_at'] = ApiClient.convertToType(data['create_at'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('distributor_id')) {
        obj['distributor_id'] = ApiClient.convertToType(data['distributor_id'], 'Number');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('images')) {
        obj['images'] = ApiClient.convertToType(data['images'], 'String');
      }
      if (data.hasOwnProperty('is_advertise')) {
        obj['is_advertise'] = ApiClient.convertToType(data['is_advertise'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('position')) {
        obj['position'] = ApiClient.convertToType(data['position'], 'Number');
      }
      if (data.hasOwnProperty('priority')) {
        obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = PresenterAdsBannerStatus.constructFromObject(data['status']);
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'Number');
      }
      if (data.hasOwnProperty('update_at')) {
        obj['update_at'] = ApiClient.convertToType(data['update_at'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} create_at
   */
  exports.prototype['create_at'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Number} distributor_id
   */
  exports.prototype['distributor_id'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} images
   */
  exports.prototype['images'] = undefined;
  /**
   * @member {Number} is_advertise
   */
  exports.prototype['is_advertise'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} position
   */
  exports.prototype['position'] = undefined;
  /**
   * @member {Number} priority
   */
  exports.prototype['priority'] = undefined;
  /**
   * @member {module:model/PresenterAdsBannerStatus} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Number} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} update_at
   */
  exports.prototype['update_at'] = undefined;



  return exports;
}));


