/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterDistributorRef'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterDistributorRef'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterTrademark = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterDistributorRef);
  }
}(this, function(ApiClient, PresenterDistributorRef) {
  'use strict';




  /**
   * The PresenterTrademark model module.
   * @module model/PresenterTrademark
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterTrademark</code>.
   * @alias module:model/PresenterTrademark
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>PresenterTrademark</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterTrademark} obj Optional instance to populate.
   * @return {module:model/PresenterTrademark} The populated <code>PresenterTrademark</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('advertise_priority')) {
        obj['advertise_priority'] = ApiClient.convertToType(data['advertise_priority'], 'Number');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('distributor')) {
        obj['distributor'] = PresenterDistributorRef.constructFromObject(data['distributor']);
      }
      if (data.hasOwnProperty('distributor_id')) {
        obj['distributor_id'] = ApiClient.convertToType(data['distributor_id'], 'Number');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('images')) {
        obj['images'] = ApiClient.convertToType(data['images'], 'String');
      }
      if (data.hasOwnProperty('is_advertise')) {
        obj['is_advertise'] = ApiClient.convertToType(data['is_advertise'], 'Boolean');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'Number');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} advertise_priority
   */
  exports.prototype['advertise_priority'] = undefined;
  /**
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {module:model/PresenterDistributorRef} distributor
   */
  exports.prototype['distributor'] = undefined;
  /**
   * @member {Number} distributor_id
   */
  exports.prototype['distributor_id'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} images
   */
  exports.prototype['images'] = undefined;
  /**
   * @member {Boolean} is_advertise
   */
  exports.prototype['is_advertise'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {String} updated_at
   */
  exports.prototype['updated_at'] = undefined;



  return exports;
}));


