/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterDistributor', 'model/PresenterSupplierStatus', 'model/PresenterSupplierType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterDistributor'), require('./PresenterSupplierStatus'), require('./PresenterSupplierType'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterSupplier = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterDistributor, root.NeomedApi.PresenterSupplierStatus, root.NeomedApi.PresenterSupplierType);
  }
}(this, function(ApiClient, PresenterDistributor, PresenterSupplierStatus, PresenterSupplierType) {
  'use strict';




  /**
   * The PresenterSupplier model module.
   * @module model/PresenterSupplier
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterSupplier</code>.
   * @alias module:model/PresenterSupplier
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>PresenterSupplier</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterSupplier} obj Optional instance to populate.
   * @return {module:model/PresenterSupplier} The populated <code>PresenterSupplier</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('create_at')) {
        obj['create_at'] = ApiClient.convertToType(data['create_at'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('display_name')) {
        obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
      }
      if (data.hasOwnProperty('distributor')) {
        obj['distributor'] = PresenterDistributor.constructFromObject(data['distributor']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('logo')) {
        obj['logo'] = ApiClient.convertToType(data['logo'], 'String');
      }
      if (data.hasOwnProperty('mail')) {
        obj['mail'] = ApiClient.convertToType(data['mail'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('phone')) {
        obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
      }
      if (data.hasOwnProperty('priority')) {
        obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
      }
      if (data.hasOwnProperty('representative')) {
        obj['representative'] = ApiClient.convertToType(data['representative'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = PresenterSupplierStatus.constructFromObject(data['status']);
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = PresenterSupplierType.constructFromObject(data['type']);
      }
      if (data.hasOwnProperty('update_at')) {
        obj['update_at'] = ApiClient.convertToType(data['update_at'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {String} create_at
   */
  exports.prototype['create_at'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} display_name
   */
  exports.prototype['display_name'] = undefined;
  /**
   * @member {module:model/PresenterDistributor} distributor
   */
  exports.prototype['distributor'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} logo
   */
  exports.prototype['logo'] = undefined;
  /**
   * @member {String} mail
   */
  exports.prototype['mail'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} phone
   */
  exports.prototype['phone'] = undefined;
  /**
   * @member {Number} priority
   */
  exports.prototype['priority'] = undefined;
  /**
   * @member {String} representative
   */
  exports.prototype['representative'] = undefined;
  /**
   * @member {module:model/PresenterSupplierStatus} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {module:model/PresenterSupplierType} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} update_at
   */
  exports.prototype['update_at'] = undefined;



  return exports;
}));


