/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterTopUpMetaItem = factory(root.NeomedApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PresenterTopUpMetaItem model module.
   * @module model/PresenterTopUpMetaItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterTopUpMetaItem</code>.
   * @alias module:model/PresenterTopUpMetaItem
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>PresenterTopUpMetaItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterTopUpMetaItem} obj Optional instance to populate.
   * @return {module:model/PresenterTopUpMetaItem} The populated <code>PresenterTopUpMetaItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('amount_limit')) {
        obj['amount_limit'] = ApiClient.convertToType(data['amount_limit'], 'Number');
      }
      if (data.hasOwnProperty('is_valid')) {
        obj['is_valid'] = ApiClient.convertToType(data['is_valid'], 'Boolean');
      }
      if (data.hasOwnProperty('promo_limit')) {
        obj['promo_limit'] = ApiClient.convertToType(data['promo_limit'], 'Number');
      }
      if (data.hasOwnProperty('promo_rate')) {
        obj['promo_rate'] = ApiClient.convertToType(data['promo_rate'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * @member {Number} amount_limit
   */
  exports.prototype['amount_limit'] = undefined;
  /**
   * @member {Boolean} is_valid
   */
  exports.prototype['is_valid'] = undefined;
  /**
   * @member {Number} promo_limit
   */
  exports.prototype['promo_limit'] = undefined;
  /**
   * @member {Number} promo_rate
   */
  exports.prototype['promo_rate'] = undefined;



  return exports;
}));


