/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterNotification', 'model/PresenterPagination'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterNotification'), require('./PresenterPagination'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterListNotiResponse = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterNotification, root.NeomedApi.PresenterPagination);
  }
}(this, function(ApiClient, PresenterNotification, PresenterPagination) {
  'use strict';




  /**
   * The PresenterListNotiResponse model module.
   * @module model/PresenterListNotiResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterListNotiResponse</code>.
   * @alias module:model/PresenterListNotiResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PresenterListNotiResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterListNotiResponse} obj Optional instance to populate.
   * @return {module:model/PresenterListNotiResponse} The populated <code>PresenterListNotiResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [PresenterNotification]);
      }
      if (data.hasOwnProperty('pagination')) {
        obj['pagination'] = PresenterPagination.constructFromObject(data['pagination']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/PresenterNotification>} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {module:model/PresenterPagination} pagination
   */
  exports.prototype['pagination'] = undefined;



  return exports;
}));


