/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterDistrict', 'model/PresenterProvince', 'model/PresenterWard'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterDistrict'), require('./PresenterProvince'), require('./PresenterWard'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterAddresss = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterDistrict, root.NeomedApi.PresenterProvince, root.NeomedApi.PresenterWard);
  }
}(this, function(ApiClient, PresenterDistrict, PresenterProvince, PresenterWard) {
  'use strict';




  /**
   * The PresenterAddresss model module.
   * @module model/PresenterAddresss
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterAddresss</code>.
   * @alias module:model/PresenterAddresss
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>PresenterAddresss</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterAddresss} obj Optional instance to populate.
   * @return {module:model/PresenterAddresss} The populated <code>PresenterAddresss</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('country_id')) {
        obj['country_id'] = ApiClient.convertToType(data['country_id'], 'String');
      }
      if (data.hasOwnProperty('district')) {
        obj['district'] = PresenterDistrict.constructFromObject(data['district']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('lat')) {
        obj['lat'] = ApiClient.convertToType(data['lat'], 'Number');
      }
      if (data.hasOwnProperty('lng')) {
        obj['lng'] = ApiClient.convertToType(data['lng'], 'Number');
      }
      if (data.hasOwnProperty('province')) {
        obj['province'] = PresenterProvince.constructFromObject(data['province']);
      }
      if (data.hasOwnProperty('street')) {
        obj['street'] = ApiClient.convertToType(data['street'], 'String');
      }
      if (data.hasOwnProperty('ward')) {
        obj['ward'] = PresenterWard.constructFromObject(data['ward']);
      }
    }
    return obj;
  }

  /**
   * @member {String} country_id
   */
  exports.prototype['country_id'] = undefined;
  /**
   * @member {module:model/PresenterDistrict} district
   */
  exports.prototype['district'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} lat
   */
  exports.prototype['lat'] = undefined;
  /**
   * @member {Number} lng
   */
  exports.prototype['lng'] = undefined;
  /**
   * @member {module:model/PresenterProvince} province
   */
  exports.prototype['province'] = undefined;
  /**
   * @member {String} street
   */
  exports.prototype['street'] = undefined;
  /**
   * @member {module:model/PresenterWard} ward
   */
  exports.prototype['ward'] = undefined;



  return exports;
}));


