/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterDiffEls'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterDiffEls'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterDiffPriceEls = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterDiffEls);
  }
}(this, function(ApiClient, PresenterDiffEls) {
  'use strict';




  /**
   * The PresenterDiffPriceEls model module.
   * @module model/PresenterDiffPriceEls
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterDiffPriceEls</code>.
   * @alias module:model/PresenterDiffPriceEls
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>PresenterDiffPriceEls</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterDiffPriceEls} obj Optional instance to populate.
   * @return {module:model/PresenterDiffPriceEls} The populated <code>PresenterDiffPriceEls</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'String');
      }
      if (data.hasOwnProperty('diff')) {
        obj['diff'] = ApiClient.convertToType(data['diff'], [PresenterDiffEls]);
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('sale_price')) {
        obj['sale_price'] = ApiClient.convertToType(data['sale_price'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} date
   */
  exports.prototype['date'] = undefined;
  /**
   * @member {Array.<module:model/PresenterDiffEls>} diff
   */
  exports.prototype['diff'] = undefined;
  /**
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {Number} sale_price
   */
  exports.prototype['sale_price'] = undefined;



  return exports;
}));


