/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterAutoCompleteKey'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterAutoCompleteKey'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterAutoCompleteSearchProducts = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterAutoCompleteKey);
  }
}(this, function(ApiClient, PresenterAutoCompleteKey) {
  'use strict';




  /**
   * The PresenterAutoCompleteSearchProducts model module.
   * @module model/PresenterAutoCompleteSearchProducts
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterAutoCompleteSearchProducts</code>.
   * @alias module:model/PresenterAutoCompleteSearchProducts
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>PresenterAutoCompleteSearchProducts</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterAutoCompleteSearchProducts} obj Optional instance to populate.
   * @return {module:model/PresenterAutoCompleteSearchProducts} The populated <code>PresenterAutoCompleteSearchProducts</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('autocomplete')) {
        obj['autocomplete'] = ApiClient.convertToType(data['autocomplete'], [PresenterAutoCompleteKey]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/PresenterAutoCompleteKey>} autocomplete
   */
  exports.prototype['autocomplete'] = undefined;



  return exports;
}));


