/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EntityError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EntityError'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterLoanConfirmResponseData = factory(root.NeomedApi.ApiClient, root.NeomedApi.EntityError);
  }
}(this, function(ApiClient, EntityError) {
  'use strict';




  /**
   * The PresenterLoanConfirmResponseData model module.
   * @module model/PresenterLoanConfirmResponseData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterLoanConfirmResponseData</code>.
   * @alias module:model/PresenterLoanConfirmResponseData
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>PresenterLoanConfirmResponseData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterLoanConfirmResponseData} obj Optional instance to populate.
   * @return {module:model/PresenterLoanConfirmResponseData} The populated <code>PresenterLoanConfirmResponseData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accountNumber')) {
        obj['accountNumber'] = ApiClient.convertToType(data['accountNumber'], 'String');
      }
      if (data.hasOwnProperty('contractdId')) {
        obj['contractdId'] = ApiClient.convertToType(data['contractdId'], 'String');
      }
      if (data.hasOwnProperty('error')) {
        obj['error'] = EntityError.constructFromObject(data['error']);
      }
      if (data.hasOwnProperty('interestRate')) {
        obj['interestRate'] = ApiClient.convertToType(data['interestRate'], 'String');
      }
      if (data.hasOwnProperty('loanTerm')) {
        obj['loanTerm'] = ApiClient.convertToType(data['loanTerm'], 'String');
      }
      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} accountNumber
   */
  exports.prototype['accountNumber'] = undefined;
  /**
   * @member {String} contractdId
   */
  exports.prototype['contractdId'] = undefined;
  /**
   * @member {module:model/EntityError} error
   */
  exports.prototype['error'] = undefined;
  /**
   * @member {String} interestRate
   */
  exports.prototype['interestRate'] = undefined;
  /**
   * @member {String} loanTerm
   */
  exports.prototype['loanTerm'] = undefined;
  /**
   * @member {String} startDate
   */
  exports.prototype['startDate'] = undefined;



  return exports;
}));


