/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterDistributor', 'model/PresenterGroupStatus', 'model/PresenterPharmacy'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterDistributor'), require('./PresenterGroupStatus'), require('./PresenterPharmacy'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterCustomerGroup = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterDistributor, root.NeomedApi.PresenterGroupStatus, root.NeomedApi.PresenterPharmacy);
  }
}(this, function(ApiClient, PresenterDistributor, PresenterGroupStatus, PresenterPharmacy) {
  'use strict';




  /**
   * The PresenterCustomerGroup model module.
   * @module model/PresenterCustomerGroup
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterCustomerGroup</code>.
   * @alias module:model/PresenterCustomerGroup
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>PresenterCustomerGroup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterCustomerGroup} obj Optional instance to populate.
   * @return {module:model/PresenterCustomerGroup} The populated <code>PresenterCustomerGroup</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('customers')) {
        obj['customers'] = ApiClient.convertToType(data['customers'], [PresenterPharmacy]);
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('distributor')) {
        obj['distributor'] = PresenterDistributor.constructFromObject(data['distributor']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = PresenterGroupStatus.constructFromObject(data['status']);
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {Array.<module:model/PresenterPharmacy>} customers
   */
  exports.prototype['customers'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {module:model/PresenterDistributor} distributor
   */
  exports.prototype['distributor'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/PresenterGroupStatus} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {String} updated_at
   */
  exports.prototype['updated_at'] = undefined;



  return exports;
}));


