/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterErrorResponse', 'model/PresenterUnlinkResourceResponseData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterErrorResponse'), require('./PresenterUnlinkResourceResponseData'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterUnlinkResourceResponse = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterErrorResponse, root.NeomedApi.PresenterUnlinkResourceResponseData);
  }
}(this, function(ApiClient, PresenterErrorResponse, PresenterUnlinkResourceResponseData) {
  'use strict';




  /**
   * The PresenterUnlinkResourceResponse model module.
   * @module model/PresenterUnlinkResourceResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterUnlinkResourceResponse</code>.
   * @alias module:model/PresenterUnlinkResourceResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PresenterUnlinkResourceResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterUnlinkResourceResponse} obj Optional instance to populate.
   * @return {module:model/PresenterUnlinkResourceResponse} The populated <code>PresenterUnlinkResourceResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = PresenterUnlinkResourceResponseData.constructFromObject(data['data']);
      }
      if (data.hasOwnProperty('errors')) {
        obj['errors'] = ApiClient.convertToType(data['errors'], [PresenterErrorResponse]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PresenterUnlinkResourceResponseData} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {Array.<module:model/PresenterErrorResponse>} errors
   */
  exports.prototype['errors'] = undefined;



  return exports;
}));


