/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterExportPaymentTx', 'model/PresenterExportTopupTx', 'model/PresenterUserReport'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterExportPaymentTx'), require('./PresenterExportTopupTx'), require('./PresenterUserReport'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterExportDataByUser = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterExportPaymentTx, root.NeomedApi.PresenterExportTopupTx, root.NeomedApi.PresenterUserReport);
  }
}(this, function(ApiClient, PresenterExportPaymentTx, PresenterExportTopupTx, PresenterUserReport) {
  'use strict';




  /**
   * The PresenterExportDataByUser model module.
   * @module model/PresenterExportDataByUser
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterExportDataByUser</code>.
   * @alias module:model/PresenterExportDataByUser
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>PresenterExportDataByUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterExportDataByUser} obj Optional instance to populate.
   * @return {module:model/PresenterExportDataByUser} The populated <code>PresenterExportDataByUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('payment_txs')) {
        obj['payment_txs'] = ApiClient.convertToType(data['payment_txs'], [PresenterExportPaymentTx]);
      }
      if (data.hasOwnProperty('point_txs')) {
        obj['point_txs'] = ApiClient.convertToType(data['point_txs'], [PresenterExportPaymentTx]);
      }
      if (data.hasOwnProperty('topup_txs')) {
        obj['topup_txs'] = ApiClient.convertToType(data['topup_txs'], [PresenterExportTopupTx]);
      }
      if (data.hasOwnProperty('total_payment_amount')) {
        obj['total_payment_amount'] = ApiClient.convertToType(data['total_payment_amount'], 'Number');
      }
      if (data.hasOwnProperty('total_payment_txs')) {
        obj['total_payment_txs'] = ApiClient.convertToType(data['total_payment_txs'], 'Number');
      }
      if (data.hasOwnProperty('total_point_amount')) {
        obj['total_point_amount'] = ApiClient.convertToType(data['total_point_amount'], 'Number');
      }
      if (data.hasOwnProperty('total_point_txs')) {
        obj['total_point_txs'] = ApiClient.convertToType(data['total_point_txs'], 'Number');
      }
      if (data.hasOwnProperty('total_topup_amount')) {
        obj['total_topup_amount'] = ApiClient.convertToType(data['total_topup_amount'], 'Number');
      }
      if (data.hasOwnProperty('total_topup_txs')) {
        obj['total_topup_txs'] = ApiClient.convertToType(data['total_topup_txs'], 'Number');
      }
      if (data.hasOwnProperty('user')) {
        obj['user'] = PresenterUserReport.constructFromObject(data['user']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/PresenterExportPaymentTx>} payment_txs
   */
  exports.prototype['payment_txs'] = undefined;
  /**
   * @member {Array.<module:model/PresenterExportPaymentTx>} point_txs
   */
  exports.prototype['point_txs'] = undefined;
  /**
   * @member {Array.<module:model/PresenterExportTopupTx>} topup_txs
   */
  exports.prototype['topup_txs'] = undefined;
  /**
   * @member {Number} total_payment_amount
   */
  exports.prototype['total_payment_amount'] = undefined;
  /**
   * @member {Number} total_payment_txs
   */
  exports.prototype['total_payment_txs'] = undefined;
  /**
   * @member {Number} total_point_amount
   */
  exports.prototype['total_point_amount'] = undefined;
  /**
   * @member {Number} total_point_txs
   */
  exports.prototype['total_point_txs'] = undefined;
  /**
   * @member {Number} total_topup_amount
   */
  exports.prototype['total_topup_amount'] = undefined;
  /**
   * @member {Number} total_topup_txs
   */
  exports.prototype['total_topup_txs'] = undefined;
  /**
   * @member {module:model/PresenterUserReport} user
   */
  exports.prototype['user'] = undefined;



  return exports;
}));


