/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterLoanInfo = factory(root.NeomedApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PresenterLoanInfo model module.
   * @module model/PresenterLoanInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterLoanInfo</code>.
   * @alias module:model/PresenterLoanInfo
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>PresenterLoanInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterLoanInfo} obj Optional instance to populate.
   * @return {module:model/PresenterLoanInfo} The populated <code>PresenterLoanInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('chargeAccount')) {
        obj['chargeAccount'] = ApiClient.convertToType(data['chargeAccount'], 'String');
      }
      if (data.hasOwnProperty('endDate')) {
        obj['endDate'] = ApiClient.convertToType(data['endDate'], 'String');
      }
      if (data.hasOwnProperty('feeOverdue')) {
        obj['feeOverdue'] = ApiClient.convertToType(data['feeOverdue'], 'Number');
      }
      if (data.hasOwnProperty('interestAccount')) {
        obj['interestAccount'] = ApiClient.convertToType(data['interestAccount'], 'String');
      }
      if (data.hasOwnProperty('interestAmount')) {
        obj['interestAmount'] = ApiClient.convertToType(data['interestAmount'], 'Number');
      }
      if (data.hasOwnProperty('interestOverdue')) {
        obj['interestOverdue'] = ApiClient.convertToType(data['interestOverdue'], 'Number');
      }
      if (data.hasOwnProperty('interestRate')) {
        obj['interestRate'] = ApiClient.convertToType(data['interestRate'], 'String');
      }
      if (data.hasOwnProperty('limitAmount')) {
        obj['limitAmount'] = ApiClient.convertToType(data['limitAmount'], 'Number');
      }
      if (data.hasOwnProperty('loanAmount')) {
        obj['loanAmount'] = ApiClient.convertToType(data['loanAmount'], 'Number');
      }
      if (data.hasOwnProperty('loanId')) {
        obj['loanId'] = ApiClient.convertToType(data['loanId'], 'String');
      }
      if (data.hasOwnProperty('loanTerm')) {
        obj['loanTerm'] = ApiClient.convertToType(data['loanTerm'], 'String');
      }
      if (data.hasOwnProperty('principalAccount')) {
        obj['principalAccount'] = ApiClient.convertToType(data['principalAccount'], 'String');
      }
      if (data.hasOwnProperty('principalOverdue')) {
        obj['principalOverdue'] = ApiClient.convertToType(data['principalOverdue'], 'Number');
      }
      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'String');
      }
      if (data.hasOwnProperty('totalOverdueAmount')) {
        obj['totalOverdueAmount'] = ApiClient.convertToType(data['totalOverdueAmount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} chargeAccount
   */
  exports.prototype['chargeAccount'] = undefined;
  /**
   * @member {String} endDate
   */
  exports.prototype['endDate'] = undefined;
  /**
   * @member {Number} feeOverdue
   */
  exports.prototype['feeOverdue'] = undefined;
  /**
   * @member {String} interestAccount
   */
  exports.prototype['interestAccount'] = undefined;
  /**
   * @member {Number} interestAmount
   */
  exports.prototype['interestAmount'] = undefined;
  /**
   * @member {Number} interestOverdue
   */
  exports.prototype['interestOverdue'] = undefined;
  /**
   * @member {String} interestRate
   */
  exports.prototype['interestRate'] = undefined;
  /**
   * @member {Number} limitAmount
   */
  exports.prototype['limitAmount'] = undefined;
  /**
   * @member {Number} loanAmount
   */
  exports.prototype['loanAmount'] = undefined;
  /**
   * @member {String} loanId
   */
  exports.prototype['loanId'] = undefined;
  /**
   * @member {String} loanTerm
   */
  exports.prototype['loanTerm'] = undefined;
  /**
   * @member {String} principalAccount
   */
  exports.prototype['principalAccount'] = undefined;
  /**
   * @member {Number} principalOverdue
   */
  exports.prototype['principalOverdue'] = undefined;
  /**
   * @member {String} startDate
   */
  exports.prototype['startDate'] = undefined;
  /**
   * @member {Number} totalOverdueAmount
   */
  exports.prototype['totalOverdueAmount'] = undefined;



  return exports;
}));


