/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterProductOptions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterProductOptions'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterNewProduct = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterProductOptions);
  }
}(this, function(ApiClient, PresenterProductOptions) {
  'use strict';




  /**
   * The PresenterNewProduct model module.
   * @module model/PresenterNewProduct
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterNewProduct</code>.
   * @alias module:model/PresenterNewProduct
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>PresenterNewProduct</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterNewProduct} obj Optional instance to populate.
   * @return {module:model/PresenterNewProduct} The populated <code>PresenterNewProduct</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('product_id')) {
        obj['product_id'] = ApiClient.convertToType(data['product_id'], 'Number');
      }
      if (data.hasOwnProperty('product_options')) {
        obj['product_options'] = PresenterProductOptions.constructFromObject(data['product_options']);
      }
      if (data.hasOwnProperty('qty')) {
        obj['qty'] = ApiClient.convertToType(data['qty'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} product_id
   */
  exports.prototype['product_id'] = undefined;
  /**
   * @member {module:model/PresenterProductOptions} product_options
   */
  exports.prototype['product_options'] = undefined;
  /**
   * @member {Number} qty
   */
  exports.prototype['qty'] = undefined;



  return exports;
}));


