/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterAccumulationOrderMeta', 'model/PresenterComboAdvanceMeta', 'model/PresenterComboMeta', 'model/PresenterDiscountBuyingProductsMeta', 'model/PresenterDiscountOrderMeta', 'model/PresenterDistributorCampaign', 'model/PresenterGiftBuyingProductsMeta', 'model/PresenterGiftOrderMeta', 'model/PresenterTopUpMeta', 'model/PresenterVoucherMeta'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterAccumulationOrderMeta'), require('./PresenterComboAdvanceMeta'), require('./PresenterComboMeta'), require('./PresenterDiscountBuyingProductsMeta'), require('./PresenterDiscountOrderMeta'), require('./PresenterDistributorCampaign'), require('./PresenterGiftBuyingProductsMeta'), require('./PresenterGiftOrderMeta'), require('./PresenterTopUpMeta'), require('./PresenterVoucherMeta'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterCampaign = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterAccumulationOrderMeta, root.NeomedApi.PresenterComboAdvanceMeta, root.NeomedApi.PresenterComboMeta, root.NeomedApi.PresenterDiscountBuyingProductsMeta, root.NeomedApi.PresenterDiscountOrderMeta, root.NeomedApi.PresenterDistributorCampaign, root.NeomedApi.PresenterGiftBuyingProductsMeta, root.NeomedApi.PresenterGiftOrderMeta, root.NeomedApi.PresenterTopUpMeta, root.NeomedApi.PresenterVoucherMeta);
  }
}(this, function(ApiClient, PresenterAccumulationOrderMeta, PresenterComboAdvanceMeta, PresenterComboMeta, PresenterDiscountBuyingProductsMeta, PresenterDiscountOrderMeta, PresenterDistributorCampaign, PresenterGiftBuyingProductsMeta, PresenterGiftOrderMeta, PresenterTopUpMeta, PresenterVoucherMeta) {
  'use strict';




  /**
   * The PresenterCampaign model module.
   * @module model/PresenterCampaign
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterCampaign</code>.
   * @alias module:model/PresenterCampaign
   * @class
   */
  var exports = function() {
    var _this = this;

































  };

  /**
   * Constructs a <code>PresenterCampaign</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterCampaign} obj Optional instance to populate.
   * @return {module:model/PresenterCampaign} The populated <code>PresenterCampaign</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accumulation_order_meta')) {
        obj['accumulation_order_meta'] = PresenterAccumulationOrderMeta.constructFromObject(data['accumulation_order_meta']);
      }
      if (data.hasOwnProperty('campaign_type')) {
        obj['campaign_type'] = ApiClient.convertToType(data['campaign_type'], 'Number');
      }
      if (data.hasOwnProperty('combo_advance_meta')) {
        obj['combo_advance_meta'] = PresenterComboAdvanceMeta.constructFromObject(data['combo_advance_meta']);
      }
      if (data.hasOwnProperty('combo_meta')) {
        obj['combo_meta'] = PresenterComboMeta.constructFromObject(data['combo_meta']);
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('customer_group')) {
        obj['customer_group'] = ApiClient.convertToType(data['customer_group'], 'Number');
      }
      if (data.hasOwnProperty('days_in_week')) {
        obj['days_in_week'] = ApiClient.convertToType(data['days_in_week'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('discount_buying_products_meta')) {
        obj['discount_buying_products_meta'] = PresenterDiscountBuyingProductsMeta.constructFromObject(data['discount_buying_products_meta']);
      }
      if (data.hasOwnProperty('discount_order_meta')) {
        obj['discount_order_meta'] = PresenterDiscountOrderMeta.constructFromObject(data['discount_order_meta']);
      }
      if (data.hasOwnProperty('distributor')) {
        obj['distributor'] = PresenterDistributorCampaign.constructFromObject(data['distributor']);
      }
      if (data.hasOwnProperty('distributor_id')) {
        obj['distributor_id'] = ApiClient.convertToType(data['distributor_id'], 'Number');
      }
      if (data.hasOwnProperty('end_date')) {
        obj['end_date'] = ApiClient.convertToType(data['end_date'], 'String');
      }
      if (data.hasOwnProperty('end_time')) {
        obj['end_time'] = ApiClient.convertToType(data['end_time'], 'String');
      }
      if (data.hasOwnProperty('gift_buying_products_meta')) {
        obj['gift_buying_products_meta'] = PresenterGiftBuyingProductsMeta.constructFromObject(data['gift_buying_products_meta']);
      }
      if (data.hasOwnProperty('gift_order_meta')) {
        obj['gift_order_meta'] = PresenterGiftOrderMeta.constructFromObject(data['gift_order_meta']);
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('images')) {
        obj['images'] = ApiClient.convertToType(data['images'], 'String');
      }
      if (data.hasOwnProperty('is_order_valid')) {
        obj['is_order_valid'] = ApiClient.convertToType(data['is_order_valid'], 'Boolean');
      }
      if (data.hasOwnProperty('meta_data')) {
        obj['meta_data'] = ApiClient.convertToType(data['meta_data'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('promo_wallet_id')) {
        obj['promo_wallet_id'] = ApiClient.convertToType(data['promo_wallet_id'], 'Number');
      }
      if (data.hasOwnProperty('promotion_fee')) {
        obj['promotion_fee'] = ApiClient.convertToType(data['promotion_fee'], 'Number');
      }
      if (data.hasOwnProperty('short_description')) {
        obj['short_description'] = ApiClient.convertToType(data['short_description'], 'String');
      }
      if (data.hasOwnProperty('spent_budget')) {
        obj['spent_budget'] = ApiClient.convertToType(data['spent_budget'], 'Number');
      }
      if (data.hasOwnProperty('start_date')) {
        obj['start_date'] = ApiClient.convertToType(data['start_date'], 'String');
      }
      if (data.hasOwnProperty('start_time')) {
        obj['start_time'] = ApiClient.convertToType(data['start_time'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'Number');
      }
      if (data.hasOwnProperty('top_up_meta')) {
        obj['top_up_meta'] = PresenterTopUpMeta.constructFromObject(data['top_up_meta']);
      }
      if (data.hasOwnProperty('total_promotion_budget')) {
        obj['total_promotion_budget'] = ApiClient.convertToType(data['total_promotion_budget'], 'Number');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
      }
      if (data.hasOwnProperty('voucher_meta')) {
        obj['voucher_meta'] = PresenterVoucherMeta.constructFromObject(data['voucher_meta']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PresenterAccumulationOrderMeta} accumulation_order_meta
   */
  exports.prototype['accumulation_order_meta'] = undefined;
  /**
   * @member {Number} campaign_type
   */
  exports.prototype['campaign_type'] = undefined;
  /**
   * @member {module:model/PresenterComboAdvanceMeta} combo_advance_meta
   */
  exports.prototype['combo_advance_meta'] = undefined;
  /**
   * @member {module:model/PresenterComboMeta} combo_meta
   */
  exports.prototype['combo_meta'] = undefined;
  /**
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {Number} customer_group
   */
  exports.prototype['customer_group'] = undefined;
  /**
   * @member {String} days_in_week
   */
  exports.prototype['days_in_week'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {module:model/PresenterDiscountBuyingProductsMeta} discount_buying_products_meta
   */
  exports.prototype['discount_buying_products_meta'] = undefined;
  /**
   * @member {module:model/PresenterDiscountOrderMeta} discount_order_meta
   */
  exports.prototype['discount_order_meta'] = undefined;
  /**
   * @member {module:model/PresenterDistributorCampaign} distributor
   */
  exports.prototype['distributor'] = undefined;
  /**
   * @member {Number} distributor_id
   */
  exports.prototype['distributor_id'] = undefined;
  /**
   * @member {String} end_date
   */
  exports.prototype['end_date'] = undefined;
  /**
   * @member {String} end_time
   */
  exports.prototype['end_time'] = undefined;
  /**
   * @member {module:model/PresenterGiftBuyingProductsMeta} gift_buying_products_meta
   */
  exports.prototype['gift_buying_products_meta'] = undefined;
  /**
   * @member {module:model/PresenterGiftOrderMeta} gift_order_meta
   */
  exports.prototype['gift_order_meta'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} images
   */
  exports.prototype['images'] = undefined;
  /**
   * @member {Boolean} is_order_valid
   */
  exports.prototype['is_order_valid'] = undefined;
  /**
   * @member {String} meta_data
   */
  exports.prototype['meta_data'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} promo_wallet_id
   */
  exports.prototype['promo_wallet_id'] = undefined;
  /**
   * @member {Number} promotion_fee
   */
  exports.prototype['promotion_fee'] = undefined;
  /**
   * @member {String} short_description
   */
  exports.prototype['short_description'] = undefined;
  /**
   * @member {Number} spent_budget
   */
  exports.prototype['spent_budget'] = undefined;
  /**
   * @member {String} start_date
   */
  exports.prototype['start_date'] = undefined;
  /**
   * @member {String} start_time
   */
  exports.prototype['start_time'] = undefined;
  /**
   * @member {Number} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {module:model/PresenterTopUpMeta} top_up_meta
   */
  exports.prototype['top_up_meta'] = undefined;
  /**
   * @member {Number} total_promotion_budget
   */
  exports.prototype['total_promotion_budget'] = undefined;
  /**
   * @member {String} updated_at
   */
  exports.prototype['updated_at'] = undefined;
  /**
   * @member {module:model/PresenterVoucherMeta} voucher_meta
   */
  exports.prototype['voucher_meta'] = undefined;



  return exports;
}));


