/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterCampaign', 'model/PresenterPromoProduct'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterCampaign'), require('./PresenterPromoProduct'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterOrderMetaData = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterCampaign, root.NeomedApi.PresenterPromoProduct);
  }
}(this, function(ApiClient, PresenterCampaign, PresenterPromoProduct) {
  'use strict';




  /**
   * The PresenterOrderMetaData model module.
   * @module model/PresenterOrderMetaData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterOrderMetaData</code>.
   * @alias module:model/PresenterOrderMetaData
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>PresenterOrderMetaData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterOrderMetaData} obj Optional instance to populate.
   * @return {module:model/PresenterOrderMetaData} The populated <code>PresenterOrderMetaData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accumulation')) {
        obj['accumulation'] = ApiClient.convertToType(data['accumulation'], 'Number');
      }
      if (data.hasOwnProperty('neo_voucher')) {
        obj['neo_voucher'] = ApiClient.convertToType(data['neo_voucher'], 'String');
      }
      if (data.hasOwnProperty('noted')) {
        obj['noted'] = ApiClient.convertToType(data['noted'], 'String');
      }
      if (data.hasOwnProperty('promo_products')) {
        obj['promo_products'] = ApiClient.convertToType(data['promo_products'], [PresenterPromoProduct]);
      }
      if (data.hasOwnProperty('promotions')) {
        obj['promotions'] = ApiClient.convertToType(data['promotions'], [PresenterCampaign]);
      }
      if (data.hasOwnProperty('sys_discount')) {
        obj['sys_discount'] = ApiClient.convertToType(data['sys_discount'], 'Number');
      }
      if (data.hasOwnProperty('voucher')) {
        obj['voucher'] = ApiClient.convertToType(data['voucher'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} accumulation
   */
  exports.prototype['accumulation'] = undefined;
  /**
   * @member {String} neo_voucher
   */
  exports.prototype['neo_voucher'] = undefined;
  /**
   * @member {String} noted
   */
  exports.prototype['noted'] = undefined;
  /**
   * @member {Array.<module:model/PresenterPromoProduct>} promo_products
   */
  exports.prototype['promo_products'] = undefined;
  /**
   * @member {Array.<module:model/PresenterCampaign>} promotions
   */
  exports.prototype['promotions'] = undefined;
  /**
   * @member {Number} sys_discount
   */
  exports.prototype['sys_discount'] = undefined;
  /**
   * @member {String} voucher
   */
  exports.prototype['voucher'] = undefined;



  return exports;
}));


