/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Model1280280xc000cd6510False'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Model1280280xc000cd6510False'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterLinkProductSuppliersRequest = factory(root.NeomedApi.ApiClient, root.NeomedApi.Model1280280xc000cd6510False);
  }
}(this, function(ApiClient, Model1280280xc000cd6510False) {
  'use strict';




  /**
   * The PresenterLinkProductSuppliersRequest model module.
   * @module model/PresenterLinkProductSuppliersRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterLinkProductSuppliersRequest</code>.
   * @alias module:model/PresenterLinkProductSuppliersRequest
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>PresenterLinkProductSuppliersRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterLinkProductSuppliersRequest} obj Optional instance to populate.
   * @return {module:model/PresenterLinkProductSuppliersRequest} The populated <code>PresenterLinkProductSuppliersRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('suppliers')) {
        obj['suppliers'] = ApiClient.convertToType(data['suppliers'], [Model1280280xc000cd6510False]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Model1280280xc000cd6510False>} suppliers
   */
  exports.prototype['suppliers'] = undefined;



  return exports;
}));


