/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterOrder'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterOrder'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterGetOneOrderResponse = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterOrder);
  }
}(this, function(ApiClient, PresenterOrder) {
  'use strict';




  /**
   * The PresenterGetOneOrderResponse model module.
   * @module model/PresenterGetOneOrderResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterGetOneOrderResponse</code>.
   * @alias module:model/PresenterGetOneOrderResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>PresenterGetOneOrderResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterGetOneOrderResponse} obj Optional instance to populate.
   * @return {module:model/PresenterGetOneOrderResponse} The populated <code>PresenterGetOneOrderResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('order')) {
        obj['order'] = PresenterOrder.constructFromObject(data['order']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PresenterOrder} order
   */
  exports.prototype['order'] = undefined;



  return exports;
}));


