/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterRefProduct = factory(root.NeomedApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PresenterRefProduct model module.
   * @module model/PresenterRefProduct
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterRefProduct</code>.
   * @alias module:model/PresenterRefProduct
   * @class
   */
  var exports = function() {
    var _this = this;
































  };

  /**
   * Constructs a <code>PresenterRefProduct</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterRefProduct} obj Optional instance to populate.
   * @return {module:model/PresenterRefProduct} The populated <code>PresenterRefProduct</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('distribution_unit')) {
        obj['distribution_unit'] = ApiClient.convertToType(data['distribution_unit'], 'String');
      }
      if (data.hasOwnProperty('distributor_id')) {
        obj['distributor_id'] = ApiClient.convertToType(data['distributor_id'], 'Number');
      }
      if (data.hasOwnProperty('dosage_forms')) {
        obj['dosage_forms'] = ApiClient.convertToType(data['dosage_forms'], 'String');
      }
      if (data.hasOwnProperty('exclusive_type')) {
        obj['exclusive_type'] = ApiClient.convertToType(data['exclusive_type'], 'Number');
      }
      if (data.hasOwnProperty('expire_date')) {
        obj['expire_date'] = ApiClient.convertToType(data['expire_date'], 'String');
      }
      if (data.hasOwnProperty('images')) {
        obj['images'] = ApiClient.convertToType(data['images'], ['String']);
      }
      if (data.hasOwnProperty('is_wishlist')) {
        obj['is_wishlist'] = ApiClient.convertToType(data['is_wishlist'], 'Boolean');
      }
      if (data.hasOwnProperty('main_ingredient')) {
        obj['main_ingredient'] = ApiClient.convertToType(data['main_ingredient'], 'String');
      }
      if (data.hasOwnProperty('manufacture')) {
        obj['manufacture'] = ApiClient.convertToType(data['manufacture'], 'String');
      }
      if (data.hasOwnProperty('medicinal_props')) {
        obj['medicinal_props'] = ApiClient.convertToType(data['medicinal_props'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('origin')) {
        obj['origin'] = ApiClient.convertToType(data['origin'], 'String');
      }
      if (data.hasOwnProperty('packing_specs')) {
        obj['packing_specs'] = ApiClient.convertToType(data['packing_specs'], 'String');
      }
      if (data.hasOwnProperty('payment_type')) {
        obj['payment_type'] = ApiClient.convertToType(data['payment_type'], 'Number');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('product_code')) {
        obj['product_code'] = ApiClient.convertToType(data['product_code'], 'String');
      }
      if (data.hasOwnProperty('product_id')) {
        obj['product_id'] = ApiClient.convertToType(data['product_id'], 'Number');
      }
      if (data.hasOwnProperty('product_status')) {
        obj['product_status'] = ApiClient.convertToType(data['product_status'], 'Number');
      }
      if (data.hasOwnProperty('product_type')) {
        obj['product_type'] = ApiClient.convertToType(data['product_type'], 'Number');
      }
      if (data.hasOwnProperty('registered_code')) {
        obj['registered_code'] = ApiClient.convertToType(data['registered_code'], 'String');
      }
      if (data.hasOwnProperty('sale_price')) {
        obj['sale_price'] = ApiClient.convertToType(data['sale_price'], 'Number');
      }
      if (data.hasOwnProperty('sale_type')) {
        obj['sale_type'] = ApiClient.convertToType(data['sale_type'], 'Number');
      }
      if (data.hasOwnProperty('short_description')) {
        obj['short_description'] = ApiClient.convertToType(data['short_description'], 'String');
      }
      if (data.hasOwnProperty('thumbnail')) {
        obj['thumbnail'] = ApiClient.convertToType(data['thumbnail'], 'String');
      }
      if (data.hasOwnProperty('trademark')) {
        obj['trademark'] = ApiClient.convertToType(data['trademark'], 'Number');
      }
      if (data.hasOwnProperty('unit')) {
        obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
      }
      if (data.hasOwnProperty('vat_applied')) {
        obj['vat_applied'] = ApiClient.convertToType(data['vat_applied'], 'Boolean');
      }
      if (data.hasOwnProperty('vat_value')) {
        obj['vat_value'] = ApiClient.convertToType(data['vat_value'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} distribution_unit
   */
  exports.prototype['distribution_unit'] = undefined;
  /**
   * @member {Number} distributor_id
   */
  exports.prototype['distributor_id'] = undefined;
  /**
   * @member {String} dosage_forms
   */
  exports.prototype['dosage_forms'] = undefined;
  /**
   * @member {Number} exclusive_type
   */
  exports.prototype['exclusive_type'] = undefined;
  /**
   * @member {String} expire_date
   */
  exports.prototype['expire_date'] = undefined;
  /**
   * @member {Array.<String>} images
   */
  exports.prototype['images'] = undefined;
  /**
   * @member {Boolean} is_wishlist
   */
  exports.prototype['is_wishlist'] = undefined;
  /**
   * @member {String} main_ingredient
   */
  exports.prototype['main_ingredient'] = undefined;
  /**
   * @member {String} manufacture
   */
  exports.prototype['manufacture'] = undefined;
  /**
   * @member {String} medicinal_props
   */
  exports.prototype['medicinal_props'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} origin
   */
  exports.prototype['origin'] = undefined;
  /**
   * @member {String} packing_specs
   */
  exports.prototype['packing_specs'] = undefined;
  /**
   * @member {Number} payment_type
   */
  exports.prototype['payment_type'] = undefined;
  /**
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {String} product_code
   */
  exports.prototype['product_code'] = undefined;
  /**
   * @member {Number} product_id
   */
  exports.prototype['product_id'] = undefined;
  /**
   * @member {Number} product_status
   */
  exports.prototype['product_status'] = undefined;
  /**
   * @member {Number} product_type
   */
  exports.prototype['product_type'] = undefined;
  /**
   * @member {String} registered_code
   */
  exports.prototype['registered_code'] = undefined;
  /**
   * @member {Number} sale_price
   */
  exports.prototype['sale_price'] = undefined;
  /**
   * @member {Number} sale_type
   */
  exports.prototype['sale_type'] = undefined;
  /**
   * @member {String} short_description
   */
  exports.prototype['short_description'] = undefined;
  /**
   * @member {String} thumbnail
   */
  exports.prototype['thumbnail'] = undefined;
  /**
   * @member {Number} trademark
   */
  exports.prototype['trademark'] = undefined;
  /**
   * @member {String} unit
   */
  exports.prototype['unit'] = undefined;
  /**
   * @member {String} updated_at
   */
  exports.prototype['updated_at'] = undefined;
  /**
   * @member {Boolean} vat_applied
   */
  exports.prototype['vat_applied'] = undefined;
  /**
   * @member {Number} vat_value
   */
  exports.prototype['vat_value'] = undefined;



  return exports;
}));


