/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterExportPaymentTx = factory(root.NeomedApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PresenterExportPaymentTx model module.
   * @module model/PresenterExportPaymentTx
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterExportPaymentTx</code>.
   * @alias module:model/PresenterExportPaymentTx
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>PresenterExportPaymentTx</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterExportPaymentTx} obj Optional instance to populate.
   * @return {module:model/PresenterExportPaymentTx} The populated <code>PresenterExportPaymentTx</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('distributor_id')) {
        obj['distributor_id'] = ApiClient.convertToType(data['distributor_id'], 'Number');
      }
      if (data.hasOwnProperty('order_id')) {
        obj['order_id'] = ApiClient.convertToType(data['order_id'], 'Number');
      }
      if (data.hasOwnProperty('payment_at')) {
        obj['payment_at'] = ApiClient.convertToType(data['payment_at'], 'String');
      }
      if (data.hasOwnProperty('payment_method')) {
        obj['payment_method'] = ApiClient.convertToType(data['payment_method'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {Number} distributor_id
   */
  exports.prototype['distributor_id'] = undefined;
  /**
   * @member {Number} order_id
   */
  exports.prototype['order_id'] = undefined;
  /**
   * @member {String} payment_at
   */
  exports.prototype['payment_at'] = undefined;
  /**
   * @member {String} payment_method
   */
  exports.prototype['payment_method'] = undefined;



  return exports;
}));


