/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterGiftBuyingProductsMetaItem', 'model/PresenterProductSnapCamp'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterGiftBuyingProductsMetaItem'), require('./PresenterProductSnapCamp'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterGiftBuyingProductsMeta = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterGiftBuyingProductsMetaItem, root.NeomedApi.PresenterProductSnapCamp);
  }
}(this, function(ApiClient, PresenterGiftBuyingProductsMetaItem, PresenterProductSnapCamp) {
  'use strict';




  /**
   * The PresenterGiftBuyingProductsMeta model module.
   * @module model/PresenterGiftBuyingProductsMeta
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterGiftBuyingProductsMeta</code>.
   * @alias module:model/PresenterGiftBuyingProductsMeta
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>PresenterGiftBuyingProductsMeta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterGiftBuyingProductsMeta} obj Optional instance to populate.
   * @return {module:model/PresenterGiftBuyingProductsMeta} The populated <code>PresenterGiftBuyingProductsMeta</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('applied_products')) {
        obj['applied_products'] = ApiClient.convertToType(data['applied_products'], [PresenterProductSnapCamp]);
      }
      if (data.hasOwnProperty('is_gift_selection')) {
        obj['is_gift_selection'] = ApiClient.convertToType(data['is_gift_selection'], 'Boolean');
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [PresenterGiftBuyingProductsMetaItem]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/PresenterProductSnapCamp>} applied_products
   */
  exports.prototype['applied_products'] = undefined;
  /**
   * @member {Boolean} is_gift_selection
   */
  exports.prototype['is_gift_selection'] = undefined;
  /**
   * @member {Array.<module:model/PresenterGiftBuyingProductsMetaItem>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


