/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterNeo = factory(root.NeomedApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PresenterNeo model module.
   * @module model/PresenterNeo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterNeo</code>.
   * @alias module:model/PresenterNeo
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>PresenterNeo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterNeo} obj Optional instance to populate.
   * @return {module:model/PresenterNeo} The populated <code>PresenterNeo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('distributor_id')) {
        obj['distributor_id'] = ApiClient.convertToType(data['distributor_id'], 'Number');
      }
      if (data.hasOwnProperty('distributor_name')) {
        obj['distributor_name'] = ApiClient.convertToType(data['distributor_name'], 'String');
      }
      if (data.hasOwnProperty('manufacture')) {
        obj['manufacture'] = ApiClient.convertToType(data['manufacture'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('packing_specs')) {
        obj['packing_specs'] = ApiClient.convertToType(data['packing_specs'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('product_id')) {
        obj['product_id'] = ApiClient.convertToType(data['product_id'], 'Number');
      }
      if (data.hasOwnProperty('registered_code')) {
        obj['registered_code'] = ApiClient.convertToType(data['registered_code'], 'String');
      }
      if (data.hasOwnProperty('sale_price')) {
        obj['sale_price'] = ApiClient.convertToType(data['sale_price'], 'Number');
      }
      if (data.hasOwnProperty('unit')) {
        obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} distributor_id
   */
  exports.prototype['distributor_id'] = undefined;
  /**
   * @member {String} distributor_name
   */
  exports.prototype['distributor_name'] = undefined;
  /**
   * @member {String} manufacture
   */
  exports.prototype['manufacture'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} packing_specs
   */
  exports.prototype['packing_specs'] = undefined;
  /**
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {Number} product_id
   */
  exports.prototype['product_id'] = undefined;
  /**
   * @member {String} registered_code
   */
  exports.prototype['registered_code'] = undefined;
  /**
   * @member {Number} sale_price
   */
  exports.prototype['sale_price'] = undefined;
  /**
   * @member {String} unit
   */
  exports.prototype['unit'] = undefined;



  return exports;
}));


