/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterAmountAndTx'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterAmountAndTx'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterCustomerPurchasing = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterAmountAndTx);
  }
}(this, function(ApiClient, PresenterAmountAndTx) {
  'use strict';




  /**
   * The PresenterCustomerPurchasing model module.
   * @module model/PresenterCustomerPurchasing
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterCustomerPurchasing</code>.
   * @alias module:model/PresenterCustomerPurchasing
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>PresenterCustomerPurchasing</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterCustomerPurchasing} obj Optional instance to populate.
   * @return {module:model/PresenterCustomerPurchasing} The populated <code>PresenterCustomerPurchasing</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('approved_at')) {
        obj['approved_at'] = ApiClient.convertToType(data['approved_at'], 'String');
      }
      if (data.hasOwnProperty('at_timelines')) {
        obj['at_timelines'] = ApiClient.convertToType(data['at_timelines'], [PresenterAmountAndTx]);
      }
      if (data.hasOwnProperty('oldest_order_created_at')) {
        obj['oldest_order_created_at'] = ApiClient.convertToType(data['oldest_order_created_at'], 'String');
      }
      if (data.hasOwnProperty('oldest_order_id')) {
        obj['oldest_order_id'] = ApiClient.convertToType(data['oldest_order_id'], 'String');
      }
      if (data.hasOwnProperty('total_amount')) {
        obj['total_amount'] = ApiClient.convertToType(data['total_amount'], 'Number');
      }
      if (data.hasOwnProperty('total_txs')) {
        obj['total_txs'] = ApiClient.convertToType(data['total_txs'], 'Number');
      }
      if (data.hasOwnProperty('un_total_amount')) {
        obj['un_total_amount'] = ApiClient.convertToType(data['un_total_amount'], 'Number');
      }
      if (data.hasOwnProperty('un_total_txs')) {
        obj['un_total_txs'] = ApiClient.convertToType(data['un_total_txs'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} approved_at
   */
  exports.prototype['approved_at'] = undefined;
  /**
   * @member {Array.<module:model/PresenterAmountAndTx>} at_timelines
   */
  exports.prototype['at_timelines'] = undefined;
  /**
   * @member {String} oldest_order_created_at
   */
  exports.prototype['oldest_order_created_at'] = undefined;
  /**
   * @member {String} oldest_order_id
   */
  exports.prototype['oldest_order_id'] = undefined;
  /**
   * @member {Number} total_amount
   */
  exports.prototype['total_amount'] = undefined;
  /**
   * @member {Number} total_txs
   */
  exports.prototype['total_txs'] = undefined;
  /**
   * @member {Number} un_total_amount
   */
  exports.prototype['un_total_amount'] = undefined;
  /**
   * @member {Number} un_total_txs
   */
  exports.prototype['un_total_txs'] = undefined;



  return exports;
}));


