/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterTrademarkAdvertise = factory(root.NeomedApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PresenterTrademarkAdvertise model module.
   * @module model/PresenterTrademarkAdvertise
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterTrademarkAdvertise</code>.
   * @alias module:model/PresenterTrademarkAdvertise
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>PresenterTrademarkAdvertise</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterTrademarkAdvertise} obj Optional instance to populate.
   * @return {module:model/PresenterTrademarkAdvertise} The populated <code>PresenterTrademarkAdvertise</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('advertise_priority')) {
        obj['advertise_priority'] = ApiClient.convertToType(data['advertise_priority'], 'Number');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('is_advertise')) {
        obj['is_advertise'] = ApiClient.convertToType(data['is_advertise'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Number} advertise_priority
   */
  exports.prototype['advertise_priority'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Boolean} is_advertise
   */
  exports.prototype['is_advertise'] = undefined;



  return exports;
}));


