/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterDistributor', 'model/PresenterOrderCustomer', 'model/PresenterOrderMetaData', 'model/PresenterPairStatus', 'model/PresenterRefInfo', 'model/PresenterStateHistory', 'model/PresenterTrackingInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterDistributor'), require('./PresenterOrderCustomer'), require('./PresenterOrderMetaData'), require('./PresenterPairStatus'), require('./PresenterRefInfo'), require('./PresenterStateHistory'), require('./PresenterTrackingInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterOrder = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterDistributor, root.NeomedApi.PresenterOrderCustomer, root.NeomedApi.PresenterOrderMetaData, root.NeomedApi.PresenterPairStatus, root.NeomedApi.PresenterRefInfo, root.NeomedApi.PresenterStateHistory, root.NeomedApi.PresenterTrackingInfo);
  }
}(this, function(ApiClient, PresenterDistributor, PresenterOrderCustomer, PresenterOrderMetaData, PresenterPairStatus, PresenterRefInfo, PresenterStateHistory, PresenterTrackingInfo) {
  'use strict';




  /**
   * The PresenterOrder model module.
   * @module model/PresenterOrder
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterOrder</code>.
   * @alias module:model/PresenterOrder
   * @class
   */
  var exports = function() {
    var _this = this;






































  };

  /**
   * Constructs a <code>PresenterOrder</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterOrder} obj Optional instance to populate.
   * @return {module:model/PresenterOrder} The populated <code>PresenterOrder</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('cancelled_reason')) {
        obj['cancelled_reason'] = ApiClient.convertToType(data['cancelled_reason'], 'String');
      }
      if (data.hasOwnProperty('cancelled_time')) {
        obj['cancelled_time'] = ApiClient.convertToType(data['cancelled_time'], 'String');
      }
      if (data.hasOwnProperty('completed_time')) {
        obj['completed_time'] = ApiClient.convertToType(data['completed_time'], 'String');
      }
      if (data.hasOwnProperty('created_time')) {
        obj['created_time'] = ApiClient.convertToType(data['created_time'], 'String');
      }
      if (data.hasOwnProperty('discount')) {
        obj['discount'] = ApiClient.convertToType(data['discount'], 'Number');
      }
      if (data.hasOwnProperty('distributor')) {
        obj['distributor'] = PresenterDistributor.constructFromObject(data['distributor']);
      }
      if (data.hasOwnProperty('fee')) {
        obj['fee'] = ApiClient.convertToType(data['fee'], 'Number');
      }
      if (data.hasOwnProperty('fulfillment_status')) {
        obj['fulfillment_status'] = ApiClient.convertToType(data['fulfillment_status'], 'Number');
      }
      if (data.hasOwnProperty('invoice')) {
        obj['invoice'] = ApiClient.convertToType(data['invoice'], 'String');
      }
      if (data.hasOwnProperty('is_cancelable')) {
        obj['is_cancelable'] = ApiClient.convertToType(data['is_cancelable'], 'Boolean');
      }
      if (data.hasOwnProperty('is_paymentable')) {
        obj['is_paymentable'] = ApiClient.convertToType(data['is_paymentable'], 'Boolean');
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], 'String');
      }
      if (data.hasOwnProperty('metadata')) {
        obj['metadata'] = PresenterOrderMetaData.constructFromObject(data['metadata']);
      }
      if (data.hasOwnProperty('next_status')) {
        obj['next_status'] = ApiClient.convertToType(data['next_status'], [PresenterPairStatus]);
      }
      if (data.hasOwnProperty('order_id')) {
        obj['order_id'] = ApiClient.convertToType(data['order_id'], 'String');
      }
      if (data.hasOwnProperty('order_status')) {
        obj['order_status'] = ApiClient.convertToType(data['order_status'], 'Number');
      }
      if (data.hasOwnProperty('paid_time')) {
        obj['paid_time'] = ApiClient.convertToType(data['paid_time'], 'String');
      }
      if (data.hasOwnProperty('payment_status')) {
        obj['payment_status'] = ApiClient.convertToType(data['payment_status'], 'Number');
      }
      if (data.hasOwnProperty('payment_type')) {
        obj['payment_type'] = ApiClient.convertToType(data['payment_type'], 'String');
      }
      if (data.hasOwnProperty('payment_type_name')) {
        obj['payment_type_name'] = ApiClient.convertToType(data['payment_type_name'], 'String');
      }
      if (data.hasOwnProperty('product_payment_type')) {
        obj['product_payment_type'] = ApiClient.convertToType(data['product_payment_type'], 'Number');
      }
      if (data.hasOwnProperty('promotion')) {
        obj['promotion'] = ApiClient.convertToType(data['promotion'], 'String');
      }
      if (data.hasOwnProperty('ref')) {
        obj['ref'] = PresenterRefInfo.constructFromObject(data['ref']);
      }
      if (data.hasOwnProperty('shipped_time')) {
        obj['shipped_time'] = ApiClient.convertToType(data['shipped_time'], 'String');
      }
      if (data.hasOwnProperty('shipping_method')) {
        obj['shipping_method'] = ApiClient.convertToType(data['shipping_method'], 'String');
      }
      if (data.hasOwnProperty('state_histories')) {
        obj['state_histories'] = ApiClient.convertToType(data['state_histories'], [PresenterStateHistory]);
      }
      if (data.hasOwnProperty('supplier')) {
        obj['supplier'] = ApiClient.convertToType(data['supplier'], 'Number');
      }
      if (data.hasOwnProperty('surcharge')) {
        obj['surcharge'] = ApiClient.convertToType(data['surcharge'], 'Number');
      }
      if (data.hasOwnProperty('sys_discount')) {
        obj['sys_discount'] = ApiClient.convertToType(data['sys_discount'], 'Number');
      }
      if (data.hasOwnProperty('total')) {
        obj['total'] = ApiClient.convertToType(data['total'], 'Number');
      }
      if (data.hasOwnProperty('total_sale')) {
        obj['total_sale'] = ApiClient.convertToType(data['total_sale'], 'Number');
      }
      if (data.hasOwnProperty('tracking_info')) {
        obj['tracking_info'] = PresenterTrackingInfo.constructFromObject(data['tracking_info']);
      }
      if (data.hasOwnProperty('trans_id')) {
        obj['trans_id'] = ApiClient.convertToType(data['trans_id'], 'String');
      }
      if (data.hasOwnProperty('updated_time')) {
        obj['updated_time'] = ApiClient.convertToType(data['updated_time'], 'String');
      }
      if (data.hasOwnProperty('user')) {
        obj['user'] = PresenterOrderCustomer.constructFromObject(data['user']);
      }
      if (data.hasOwnProperty('user_id')) {
        obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {String} cancelled_reason
   */
  exports.prototype['cancelled_reason'] = undefined;
  /**
   * @member {String} cancelled_time
   */
  exports.prototype['cancelled_time'] = undefined;
  /**
   * @member {String} completed_time
   */
  exports.prototype['completed_time'] = undefined;
  /**
   * @member {String} created_time
   */
  exports.prototype['created_time'] = undefined;
  /**
   * @member {Number} discount
   */
  exports.prototype['discount'] = undefined;
  /**
   * @member {module:model/PresenterDistributor} distributor
   */
  exports.prototype['distributor'] = undefined;
  /**
   * @member {Number} fee
   */
  exports.prototype['fee'] = undefined;
  /**
   * @member {Number} fulfillment_status
   */
  exports.prototype['fulfillment_status'] = undefined;
  /**
   * @member {String} invoice
   */
  exports.prototype['invoice'] = undefined;
  /**
   * @member {Boolean} is_cancelable
   */
  exports.prototype['is_cancelable'] = undefined;
  /**
   * @member {Boolean} is_paymentable
   */
  exports.prototype['is_paymentable'] = undefined;
  /**
   * @member {String} items
   */
  exports.prototype['items'] = undefined;
  /**
   * @member {module:model/PresenterOrderMetaData} metadata
   */
  exports.prototype['metadata'] = undefined;
  /**
   * @member {Array.<module:model/PresenterPairStatus>} next_status
   */
  exports.prototype['next_status'] = undefined;
  /**
   * @member {String} order_id
   */
  exports.prototype['order_id'] = undefined;
  /**
   * @member {Number} order_status
   */
  exports.prototype['order_status'] = undefined;
  /**
   * @member {String} paid_time
   */
  exports.prototype['paid_time'] = undefined;
  /**
   * @member {Number} payment_status
   */
  exports.prototype['payment_status'] = undefined;
  /**
   * @member {String} payment_type
   */
  exports.prototype['payment_type'] = undefined;
  /**
   * @member {String} payment_type_name
   */
  exports.prototype['payment_type_name'] = undefined;
  /**
   * @member {Number} product_payment_type
   */
  exports.prototype['product_payment_type'] = undefined;
  /**
   * @member {String} promotion
   */
  exports.prototype['promotion'] = undefined;
  /**
   * @member {module:model/PresenterRefInfo} ref
   */
  exports.prototype['ref'] = undefined;
  /**
   * @member {String} shipped_time
   */
  exports.prototype['shipped_time'] = undefined;
  /**
   * @member {String} shipping_method
   */
  exports.prototype['shipping_method'] = undefined;
  /**
   * @member {Array.<module:model/PresenterStateHistory>} state_histories
   */
  exports.prototype['state_histories'] = undefined;
  /**
   * @member {Number} supplier
   */
  exports.prototype['supplier'] = undefined;
  /**
   * @member {Number} surcharge
   */
  exports.prototype['surcharge'] = undefined;
  /**
   * @member {Number} sys_discount
   */
  exports.prototype['sys_discount'] = undefined;
  /**
   * @member {Number} total
   */
  exports.prototype['total'] = undefined;
  /**
   * @member {Number} total_sale
   */
  exports.prototype['total_sale'] = undefined;
  /**
   * @member {module:model/PresenterTrackingInfo} tracking_info
   */
  exports.prototype['tracking_info'] = undefined;
  /**
   * @member {String} trans_id
   */
  exports.prototype['trans_id'] = undefined;
  /**
   * @member {String} updated_time
   */
  exports.prototype['updated_time'] = undefined;
  /**
   * @member {module:model/PresenterOrderCustomer} user
   */
  exports.prototype['user'] = undefined;
  /**
   * @member {String} user_id
   */
  exports.prototype['user_id'] = undefined;



  return exports;
}));


