/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterStateHistory'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterStateHistory'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterGetStateHistoryResponse = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterStateHistory);
  }
}(this, function(ApiClient, PresenterStateHistory) {
  'use strict';




  /**
   * The PresenterGetStateHistoryResponse model module.
   * @module model/PresenterGetStateHistoryResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterGetStateHistoryResponse</code>.
   * @alias module:model/PresenterGetStateHistoryResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PresenterGetStateHistoryResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterGetStateHistoryResponse} obj Optional instance to populate.
   * @return {module:model/PresenterGetStateHistoryResponse} The populated <code>PresenterGetStateHistoryResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('order_id')) {
        obj['order_id'] = ApiClient.convertToType(data['order_id'], 'String');
      }
      if (data.hasOwnProperty('state_histories')) {
        obj['state_histories'] = ApiClient.convertToType(data['state_histories'], [PresenterStateHistory]);
      }
    }
    return obj;
  }

  /**
   * @member {String} order_id
   */
  exports.prototype['order_id'] = undefined;
  /**
   * @member {Array.<module:model/PresenterStateHistory>} state_histories
   */
  exports.prototype['state_histories'] = undefined;



  return exports;
}));


