/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterCheckEventResponse = factory(root.NeomedApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PresenterCheckEventResponse model module.
   * @module model/PresenterCheckEventResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterCheckEventResponse</code>.
   * @alias module:model/PresenterCheckEventResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PresenterCheckEventResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterCheckEventResponse} obj Optional instance to populate.
   * @return {module:model/PresenterCheckEventResponse} The populated <code>PresenterCheckEventResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('is_used')) {
        obj['is_used'] = ApiClient.convertToType(data['is_used'], 'Boolean');
      }
      if (data.hasOwnProperty('ref_code')) {
        obj['ref_code'] = ApiClient.convertToType(data['ref_code'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} is_used
   */
  exports.prototype['is_used'] = undefined;
  /**
   * @member {String} ref_code
   */
  exports.prototype['ref_code'] = undefined;



  return exports;
}));


