/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterDiffPriceResources', 'model/PresenterPagination'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PresenterDiffPriceResources'), require('./PresenterPagination'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PresenterListImportResourcesProduct = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterDiffPriceResources, root.NeomedApi.PresenterPagination);
  }
}(this, function(ApiClient, PresenterDiffPriceResources, PresenterPagination) {
  'use strict';




  /**
   * The PresenterListImportResourcesProduct model module.
   * @module model/PresenterListImportResourcesProduct
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PresenterListImportResourcesProduct</code>.
   * @alias module:model/PresenterListImportResourcesProduct
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PresenterListImportResourcesProduct</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PresenterListImportResourcesProduct} obj Optional instance to populate.
   * @return {module:model/PresenterListImportResourcesProduct} The populated <code>PresenterListImportResourcesProduct</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('imports')) {
        obj['imports'] = ApiClient.convertToType(data['imports'], [PresenterDiffPriceResources]);
      }
      if (data.hasOwnProperty('pagination')) {
        obj['pagination'] = PresenterPagination.constructFromObject(data['pagination']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/PresenterDiffPriceResources>} imports
   */
  exports.prototype['imports'] = undefined;
  /**
   * @member {module:model/PresenterPagination} pagination
   */
  exports.prototype['pagination'] = undefined;



  return exports;
}));


