import { Platform, StyleSheet } from 'react-native'
import Colors from '~/common/Colors/Colors'
import dimension from '~/constants/dimens'
import { s, fs } from '~/utils/responsive'
import { brandColors, brandShadow } from '~/design-system/tokens'

export default StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: brandColors.background,
    display: 'flex',
    justifyContent: 'space-between',
    paddingTop: s(4),
  },
  imagePaginationContainer: {
    height: 24,
    width: 50,
    borderRadius: 35,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 10,
    right: dimension.common.WINDOW_WIDTH / 2 - 12,
  },
  paginationNumber: {
    color: Colors.white,
    fontSize: 12,
  },
  swiperItemContainer: {
    backgroundColor: 'transparent',
    height: dimension.common.WINDOW_HEIGHT * 0.23,
    alignItems: 'center',
  },
  swiperItem: {
    width: dimension.common.WINDOW_WIDTH,
    height: dimension.common.WINDOW_WIDTH * 2 / 3,
  },
  productInfoContainer: {
    flex: 2,
    flexDirection: 'column',
    backgroundColor: brandColors.surface,
    justifyContent: 'space-around',
    padding: s(18),
  },
  productContainer: {
    marginHorizontal: s(16),
    marginTop: s(10),
    marginBottom: s(12),
    backgroundColor: brandColors.surface,
    borderRadius: s(24),
    overflow: 'hidden',
    ...brandShadow.soft,
  },
  purchasePanel: {
    marginHorizontal: s(16),
    backgroundColor: brandColors.surface,
    borderRadius: s(24),
    padding: s(18),
    borderWidth: 1,
    borderColor: brandColors.borderSoft,
    ...brandShadow.soft,
  },
  purchaseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  metaLabel: {
    color: brandColors.mutedLight,
    fontSize: fs(10),
    fontWeight: '800',
    textTransform: 'uppercase',
    marginBottom: s(4),
  },
  discountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: s(8),
  },

  quantityContainer: {
    display: 'flex',
    backgroundColor: brandColors.surface,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: s(18),
    paddingBottom: 0
  },
  btnAddContainer: {
    margin: 0,
    flexDirection: 'row',
    paddingHorizontal: 0,
    marginHorizontal: 0,
    marginBottom: 0,
    marginTop: s(16),
  },
  btnAdd: {
    borderRadius: s(18),
    backgroundColor: brandColors.tealPrimary,
    flex: 1,
  },
  btnAddText: {
    fontSize: fs(14),
    fontWeight: '900',
  },
  quantityBtnContainer: {
    flexDirection: 'row',
    margin: 0,
    padding: 0,
    alignItems: 'center',
    paddingHorizontal: 0,
  },
  quantityBtn: {
    height: 36,
    width: 36,
    padding: 0,
    paddingHorizontal: 0,
    borderRadius: 36,
    backgroundColor: brandColors.tealLight,
  },
  productQuantityContainer: {
    borderRadius: 28,
    width: 84,
    marginHorizontal: 8,
    textAlignVertical: 'center',
    textAlign: 'center',
    fontSize: 14,
    color: brandColors.muted,
  },
  inputContainerStyle: {
    display: 'flex',
    justifyContent: 'center',
    borderRadius: 28,
    alignItems: 'center',
  },
  labelStyle: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  productQuantity: {
    textAlignVertical: 'center',
    textAlign: 'center',
    fontSize: 14,
    color: brandColors.textDark,
  },
  title: {
    color: brandColors.textDark,
    fontWeight: 'bold',
    marginBottom: 6,
    marginRight: 18,
    fontSize: fs(16),
  },
  pack: {
    color: brandColors.muted,
    fontSize: fs(14),
    fontWeight: '700',
    lineHeight: 22,
  },
  sectiontitle: {
    fontSize: 14,
    fontWeight: '700',
    color: brandColors.textDark,
  },
  swiperConatainer: {
    backgroundColor: brandColors.background,
    height: (dimension.common.WINDOW_WIDTH - 36) * 2 / 3,
    marginBottom: 1,
  },
  priceInfoContainer: {
    flexDirection: 'row',
    backgroundColor: brandColors.surface,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  priceContainer: {
    borderRadius: 36,
    borderColor: brandColors.goldAccent,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  productPrice: {
    color: brandColors.goldAccent,
    fontSize: fs(24),
    fontWeight: '900',
  },
  discount: {
    fontSize: fs(14),
    color: brandColors.mutedLight,
    fontWeight: '500',
    // lineHeight: 20,
    textDecorationLine: 'line-through',
    marginLeft: 0,
  },
  discountPercent: {
    marginLeft: s(10),
    color: brandColors.danger,
    fontSize: fs(13),
    fontWeight: '800',
  },
  actionCountContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  actionCountItemContainer: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: 18,
  },
  countValue: {
    marginLeft: 8,
  },
  rangePricesContainer: {
    flex: 1,
    padding: 18,
    backgroundColor: brandColors.surface,
    marginBottom: 8,
  },
  promotionTitle: {
    color: brandColors.textDark,
    textAlign: 'left',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '700',
    marginBottom: 12,
  },
  infoSectionTitle: {
    color: brandColors.textDark,
    textAlign: 'left',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '700',
    marginBottom: 18,
    marginHorizontal: 18,
  },
  tabTitle: {
    display: 'flex',
    flexDirection: 'row',
    borderRadius: 42,
    paddingVertical: 6,
    paddingHorizontal: 16,
    padding: 4,
    alignSelf: 'center',
  },
  tabSelected: {
    backgroundColor: Colors.white,
    color: brandColors.tealPrimary,
    fontWeight: '700',
  },
  tabContainer: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: brandColors.tealLight,
    borderRadius: 42,
    padding: 4,
    alignSelf: 'center',
    marginBottom: 18,
  },
  tabText: {
    color: brandColors.textDark,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 22,
  },
  modalContainer: {
    flex: 1,
    width: dimension.common.WINDOW_WIDTH,
    height: dimension.common.WINDOW_HEIGHT,
  },
  buttonClose: {
    position: 'absolute',
    top: Platform.OS == 'android' ? 10 : 50,
    left: 10,
  },
})
