/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterBanner', 'model/PresenterBannerMultiRequest', 'model/PresenterCreateBannerUpdateRequest', 'model/PresenterListBannersResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PresenterBanner'), require('../model/PresenterBannerMultiRequest'), require('../model/PresenterCreateBannerUpdateRequest'), require('../model/PresenterListBannersResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.BannersApi = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterBanner, root.NeomedApi.PresenterBannerMultiRequest, root.NeomedApi.PresenterCreateBannerUpdateRequest, root.NeomedApi.PresenterListBannersResponse);
  }
}(this, function(ApiClient, PresenterBanner, PresenterBannerMultiRequest, PresenterCreateBannerUpdateRequest, PresenterListBannersResponse) {
  'use strict';

  /**
   * Banners service.
   * @module api/BannersApi
   * @version 1.0.0
   */

  /**
   * Constructs a new BannersApi. 
   * @alias module:api/BannersApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the bannerControllerCreateMulti operation.
     * @callback module:api/BannersApi~bannerControllerCreateMultiCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create Banner &lt;br&gt;
     * @param {module:model/PresenterBannerMultiRequest} body body for Banner content
     * @param {module:api/BannersApi~bannerControllerCreateMultiCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.bannerControllerCreateMulti = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling bannerControllerCreateMulti");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/banners/multi/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bannerControllerDelete operation.
     * @callback module:api/BannersApi~bannerControllerDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete the Banner &lt;br&gt;
     * @param {String} id The id you want to delete
     * @param {module:api/BannersApi~bannerControllerDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.bannerControllerDelete = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling bannerControllerDelete");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/banners/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bannerControllerGetAll operation.
     * @callback module:api/BannersApi~bannerControllerGetAllCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListBannersResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Banner &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/BannersApi~bannerControllerGetAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListBannersResponse}
     */
    this.bannerControllerGetAll = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListBannersResponse;

      return this.apiClient.callApi(
        '/banners/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bannerControllerGetOne operation.
     * @callback module:api/BannersApi~bannerControllerGetOneCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterBanner} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Banner by id &lt;br&gt;
     * @param {String} id The key for staticblock
     * @param {module:api/BannersApi~bannerControllerGetOneCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterBanner}
     */
    this.bannerControllerGetOne = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling bannerControllerGetOne");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterBanner;

      return this.apiClient.callApi(
        '/banners/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bannerControllerListBannerByCampaign operation.
     * @callback module:api/BannersApi~bannerControllerListBannerByCampaignCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListBannersResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Banners &lt;br&gt;
     * @param {String} campaignId campaignId
     * @param {Object} opts Optional parameters
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/BannersApi~bannerControllerListBannerByCampaignCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListBannersResponse}
     */
    this.bannerControllerListBannerByCampaign = function(campaignId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'campaignId' is set
      if (campaignId === undefined || campaignId === null) {
        throw new Error("Missing the required parameter 'campaignId' when calling bannerControllerListBannerByCampaign");
      }


      var pathParams = {
        'campaignId': campaignId
      };
      var queryParams = {
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListBannersResponse;

      return this.apiClient.callApi(
        '/banners/campaigns/{campaignId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bannerControllerListBannerByCampaignActive operation.
     * @callback module:api/BannersApi~bannerControllerListBannerByCampaignActiveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListBannersResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Banners &lt;br&gt;
     * @param {String} distributorId distributorId
     * @param {Object} opts Optional parameters
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/BannersApi~bannerControllerListBannerByCampaignActiveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListBannersResponse}
     */
    this.bannerControllerListBannerByCampaignActive = function(distributorId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'distributorId' is set
      if (distributorId === undefined || distributorId === null) {
        throw new Error("Missing the required parameter 'distributorId' when calling bannerControllerListBannerByCampaignActive");
      }


      var pathParams = {
        'distributorId': distributorId
      };
      var queryParams = {
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListBannersResponse;

      return this.apiClient.callApi(
        '/banners/distributors/{distributorId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bannerControllerListBannersByActiveCampaignAndCampaignType operation.
     * @callback module:api/BannersApi~bannerControllerListBannersByActiveCampaignAndCampaignTypeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListBannersResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Banners &lt;br&gt;
     * @param {String} distributorId distributorId
     * @param {String} campaignType campaignType
     * @param {Object} opts Optional parameters
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/BannersApi~bannerControllerListBannersByActiveCampaignAndCampaignTypeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListBannersResponse}
     */
    this.bannerControllerListBannersByActiveCampaignAndCampaignType = function(distributorId, campaignType, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'distributorId' is set
      if (distributorId === undefined || distributorId === null) {
        throw new Error("Missing the required parameter 'distributorId' when calling bannerControllerListBannersByActiveCampaignAndCampaignType");
      }

      // verify the required parameter 'campaignType' is set
      if (campaignType === undefined || campaignType === null) {
        throw new Error("Missing the required parameter 'campaignType' when calling bannerControllerListBannersByActiveCampaignAndCampaignType");
      }


      var pathParams = {
        'distributorId': distributorId,
        'campaignType': campaignType
      };
      var queryParams = {
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListBannersResponse;

      return this.apiClient.callApi(
        '/banners/distributors/{distributorId}/type/{campaignType}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bannerControllerPost operation.
     * @callback module:api/BannersApi~bannerControllerPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create Banner &lt;br&gt;
     * @param {module:model/PresenterCreateBannerUpdateRequest} body body for Banner content
     * @param {module:api/BannersApi~bannerControllerPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.bannerControllerPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling bannerControllerPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/banners/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the bannerControllerPut operation.
     * @callback module:api/BannersApi~bannerControllerPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCreateBannerUpdateRequest} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update the Banner &lt;br&gt;
     * @param {String} id The id you want to update
     * @param {module:model/PresenterCreateBannerUpdateRequest} body body for Banner content
     * @param {module:api/BannersApi~bannerControllerPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCreateBannerUpdateRequest}
     */
    this.bannerControllerPut = function(id, body, callback) {
      var postBody = body;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling bannerControllerPut");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling bannerControllerPut");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCreateBannerUpdateRequest;

      return this.apiClient.callApi(
        '/banners/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
