/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterBOTopUpRequest', 'model/PresenterBOTopUpResponse', 'model/PresenterBalanceAccountResponse', 'model/PresenterCheckLoanResponse', 'model/PresenterGetChargeFeeResponse', 'model/PresenterGetCustomerInfoResponse', 'model/PresenterGetLoanInfoResponse', 'model/PresenterGetProposalsResponse', 'model/PresenterLinkResourceConfirmRequest', 'model/PresenterLinkResourceConfirmResponse', 'model/PresenterLinkResourceRequestResponse', 'model/PresenterListPaymentAccountResponse', 'model/PresenterLoanConfirmRequest', 'model/PresenterLoanConfirmResponse', 'model/PresenterLoanRequestRequest', 'model/PresenterLoanRequestResponse', 'model/PresenterLogEventResponse', 'model/PresenterPreCloseConfirmRequest', 'model/PresenterPreCloseConfirmResponse', 'model/PresenterPreCloseRequestResponse', 'model/PresenterRegisterConfirmRequest', 'model/PresenterRegisterConfirmResponse', 'model/PresenterRegisterRequestResponse', 'model/PresenterTopUpConfirmRequest', 'model/PresenterTopUpConfirmResponse', 'model/PresenterTopUpRequest', 'model/PresenterTopUpRequestResponse', 'model/PresenterUnlinkPaymentAccountReq', 'model/PresenterUnlinkResourceRequest', 'model/PresenterUnlinkResourceResponse', 'model/PresenterWalletInfoResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PresenterBOTopUpRequest'), require('../model/PresenterBOTopUpResponse'), require('../model/PresenterBalanceAccountResponse'), require('../model/PresenterCheckLoanResponse'), require('../model/PresenterGetChargeFeeResponse'), require('../model/PresenterGetCustomerInfoResponse'), require('../model/PresenterGetLoanInfoResponse'), require('../model/PresenterGetProposalsResponse'), require('../model/PresenterLinkResourceConfirmRequest'), require('../model/PresenterLinkResourceConfirmResponse'), require('../model/PresenterLinkResourceRequestResponse'), require('../model/PresenterListPaymentAccountResponse'), require('../model/PresenterLoanConfirmRequest'), require('../model/PresenterLoanConfirmResponse'), require('../model/PresenterLoanRequestRequest'), require('../model/PresenterLoanRequestResponse'), require('../model/PresenterLogEventResponse'), require('../model/PresenterPreCloseConfirmRequest'), require('../model/PresenterPreCloseConfirmResponse'), require('../model/PresenterPreCloseRequestResponse'), require('../model/PresenterRegisterConfirmRequest'), require('../model/PresenterRegisterConfirmResponse'), require('../model/PresenterRegisterRequestResponse'), require('../model/PresenterTopUpConfirmRequest'), require('../model/PresenterTopUpConfirmResponse'), require('../model/PresenterTopUpRequest'), require('../model/PresenterTopUpRequestResponse'), require('../model/PresenterUnlinkPaymentAccountReq'), require('../model/PresenterUnlinkResourceRequest'), require('../model/PresenterUnlinkResourceResponse'), require('../model/PresenterWalletInfoResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.EwalletApi = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterBOTopUpRequest, root.NeomedApi.PresenterBOTopUpResponse, root.NeomedApi.PresenterBalanceAccountResponse, root.NeomedApi.PresenterCheckLoanResponse, root.NeomedApi.PresenterGetChargeFeeResponse, root.NeomedApi.PresenterGetCustomerInfoResponse, root.NeomedApi.PresenterGetLoanInfoResponse, root.NeomedApi.PresenterGetProposalsResponse, root.NeomedApi.PresenterLinkResourceConfirmRequest, root.NeomedApi.PresenterLinkResourceConfirmResponse, root.NeomedApi.PresenterLinkResourceRequestResponse, root.NeomedApi.PresenterListPaymentAccountResponse, root.NeomedApi.PresenterLoanConfirmRequest, root.NeomedApi.PresenterLoanConfirmResponse, root.NeomedApi.PresenterLoanRequestRequest, root.NeomedApi.PresenterLoanRequestResponse, root.NeomedApi.PresenterLogEventResponse, root.NeomedApi.PresenterPreCloseConfirmRequest, root.NeomedApi.PresenterPreCloseConfirmResponse, root.NeomedApi.PresenterPreCloseRequestResponse, root.NeomedApi.PresenterRegisterConfirmRequest, root.NeomedApi.PresenterRegisterConfirmResponse, root.NeomedApi.PresenterRegisterRequestResponse, root.NeomedApi.PresenterTopUpConfirmRequest, root.NeomedApi.PresenterTopUpConfirmResponse, root.NeomedApi.PresenterTopUpRequest, root.NeomedApi.PresenterTopUpRequestResponse, root.NeomedApi.PresenterUnlinkPaymentAccountReq, root.NeomedApi.PresenterUnlinkResourceRequest, root.NeomedApi.PresenterUnlinkResourceResponse, root.NeomedApi.PresenterWalletInfoResponse);
  }
}(this, function(ApiClient, PresenterBOTopUpRequest, PresenterBOTopUpResponse, PresenterBalanceAccountResponse, PresenterCheckLoanResponse, PresenterGetChargeFeeResponse, PresenterGetCustomerInfoResponse, PresenterGetLoanInfoResponse, PresenterGetProposalsResponse, PresenterLinkResourceConfirmRequest, PresenterLinkResourceConfirmResponse, PresenterLinkResourceRequestResponse, PresenterListPaymentAccountResponse, PresenterLoanConfirmRequest, PresenterLoanConfirmResponse, PresenterLoanRequestRequest, PresenterLoanRequestResponse, PresenterLogEventResponse, PresenterPreCloseConfirmRequest, PresenterPreCloseConfirmResponse, PresenterPreCloseRequestResponse, PresenterRegisterConfirmRequest, PresenterRegisterConfirmResponse, PresenterRegisterRequestResponse, PresenterTopUpConfirmRequest, PresenterTopUpConfirmResponse, PresenterTopUpRequest, PresenterTopUpRequestResponse, PresenterUnlinkPaymentAccountReq, PresenterUnlinkResourceRequest, PresenterUnlinkResourceResponse, PresenterWalletInfoResponse) {
  'use strict';

  /**
   * Ewallet service.
   * @module api/EwalletApi
   * @version 1.0.0
   */

  /**
   * Constructs a new EwalletApi. 
   * @alias module:api/EwalletApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the ewalletControllerConfirmPaymentAccount operation.
     * @callback module:api/EwalletApi~ewalletControllerConfirmPaymentAccountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterRegisterConfirmResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create Ewallet &lt;br&gt;
     * @param {module:model/PresenterRegisterConfirmRequest} body body for Ewallet content
     * @param {module:api/EwalletApi~ewalletControllerConfirmPaymentAccountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterRegisterConfirmResponse}
     */
    this.ewalletControllerConfirmPaymentAccount = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling ewalletControllerConfirmPaymentAccount");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PresenterRegisterConfirmResponse;

      return this.apiClient.callApi(
        '/ewallet/confirm-linked-payment-account', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerCreatePaymentAccount operation.
     * @callback module:api/EwalletApi~ewalletControllerCreatePaymentAccountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterRegisterRequestResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create Ewallet &lt;br&gt;
     * @param {module:api/EwalletApi~ewalletControllerCreatePaymentAccountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterRegisterRequestResponse}
     */
    this.ewalletControllerCreatePaymentAccount = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterRegisterRequestResponse;

      return this.apiClient.callApi(
        '/ewallet/linked-payment-account', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerGetBalances operation.
     * @callback module:api/EwalletApi~ewalletControllerGetBalancesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterBalanceAccountResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetBalances &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {Number} opts.payment payment_enable
     * @param {module:api/EwalletApi~ewalletControllerGetBalancesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterBalanceAccountResponse}
     */
    this.ewalletControllerGetBalances = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'payment': opts['payment']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterBalanceAccountResponse;

      return this.apiClient.callApi(
        '/ewallet/get-balances', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerGetBalancesBO operation.
     * @callback module:api/EwalletApi~ewalletControllerGetBalancesBOCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterBalanceAccountResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetBalancesBO &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {String} opts.userId User id. Must be an integer
     * @param {module:api/EwalletApi~ewalletControllerGetBalancesBOCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterBalanceAccountResponse}
     */
    this.ewalletControllerGetBalancesBO = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'userId': opts['userId']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterBalanceAccountResponse;

      return this.apiClient.callApi(
        '/ewallet/bo-get-balances', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerGetChargeFee operation.
     * @callback module:api/EwalletApi~ewalletControllerGetChargeFeeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterGetChargeFeeResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetChargeFee &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {Number} opts.amount Must be an integer
     * @param {Number} opts.action Must be an integer
     * @param {module:api/EwalletApi~ewalletControllerGetChargeFeeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterGetChargeFeeResponse}
     */
    this.ewalletControllerGetChargeFee = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'amount': opts['amount'],
        'action': opts['action']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterGetChargeFeeResponse;

      return this.apiClient.callApi(
        '/ewallet/charge-fee', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerGetCheckLoan operation.
     * @callback module:api/EwalletApi~ewalletControllerGetCheckLoanCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCheckLoanResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetCheckLoan &lt;br&gt;
     * @param {module:api/EwalletApi~ewalletControllerGetCheckLoanCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCheckLoanResponse}
     */
    this.ewalletControllerGetCheckLoan = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCheckLoanResponse;

      return this.apiClient.callApi(
        '/ewallet/loan-check', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerGetCustomerInfoCurrentUser operation.
     * @callback module:api/EwalletApi~ewalletControllerGetCustomerInfoCurrentUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterGetCustomerInfoResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetCustomerInfo &lt;br&gt;
     * @param {module:api/EwalletApi~ewalletControllerGetCustomerInfoCurrentUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterGetCustomerInfoResponse}
     */
    this.ewalletControllerGetCustomerInfoCurrentUser = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterGetCustomerInfoResponse;

      return this.apiClient.callApi(
        '/ewallet/customer-info', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerGetLinkResourceRequest operation.
     * @callback module:api/EwalletApi~ewalletControllerGetLinkResourceRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterLinkResourceRequestResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetLinkResourceRequest &lt;br&gt;
     * @param {module:api/EwalletApi~ewalletControllerGetLinkResourceRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterLinkResourceRequestResponse}
     */
    this.ewalletControllerGetLinkResourceRequest = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PresenterLinkResourceRequestResponse;

      return this.apiClient.callApi(
        '/ewallet/link-resource-request', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerGetLinkedPaymentAccount operation.
     * @callback module:api/EwalletApi~ewalletControllerGetLinkedPaymentAccountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListPaymentAccountResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetLinkedPaymentAccount &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/EwalletApi~ewalletControllerGetLinkedPaymentAccountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListPaymentAccountResponse}
     */
    this.ewalletControllerGetLinkedPaymentAccount = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListPaymentAccountResponse;

      return this.apiClient.callApi(
        '/ewallet/get-linked-payment-account', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerGetLoanInfoCurrentUser operation.
     * @callback module:api/EwalletApi~ewalletControllerGetLoanInfoCurrentUserCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterGetLoanInfoResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetLoanInfo &lt;br&gt;
     * @param {module:api/EwalletApi~ewalletControllerGetLoanInfoCurrentUserCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterGetLoanInfoResponse}
     */
    this.ewalletControllerGetLoanInfoCurrentUser = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterGetLoanInfoResponse;

      return this.apiClient.callApi(
        '/ewallet/loan-info', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerGetOne operation.
     * @callback module:api/EwalletApi~ewalletControllerGetOneCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterWalletInfoResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Ewallet &lt;br&gt;
     * @param {module:api/EwalletApi~ewalletControllerGetOneCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterWalletInfoResponse}
     */
    this.ewalletControllerGetOne = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterWalletInfoResponse;

      return this.apiClient.callApi(
        '/ewallet/info', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerGetPreCloseRequest operation.
     * @callback module:api/EwalletApi~ewalletControllerGetPreCloseRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterPreCloseRequestResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetPreCloseRequest &lt;br&gt;
     * @param {module:api/EwalletApi~ewalletControllerGetPreCloseRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterPreCloseRequestResponse}
     */
    this.ewalletControllerGetPreCloseRequest = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PresenterPreCloseRequestResponse;

      return this.apiClient.callApi(
        '/ewallet/pre-close-request', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerGetProposals operation.
     * @callback module:api/EwalletApi~ewalletControllerGetProposalsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterGetProposalsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetProposals &lt;br&gt;
     * @param {module:api/EwalletApi~ewalletControllerGetProposalsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterGetProposalsResponse}
     */
    this.ewalletControllerGetProposals = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterGetProposalsResponse;

      return this.apiClient.callApi(
        '/ewallet/proposals', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerGetTransHistory operation.
     * @callback module:api/EwalletApi~ewalletControllerGetTransHistoryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterLogEventResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetTransHistory &lt;br&gt;
     * @param {String} type history type: all, topup...
     * @param {Object} opts Optional parameters
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/EwalletApi~ewalletControllerGetTransHistoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterLogEventResponse}
     */
    this.ewalletControllerGetTransHistory = function(type, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'type' is set
      if (type === undefined || type === null) {
        throw new Error("Missing the required parameter 'type' when calling ewalletControllerGetTransHistory");
      }


      var pathParams = {
      };
      var queryParams = {
        'type': type,
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterLogEventResponse;

      return this.apiClient.callApi(
        '/ewallet/get-trans-his', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerListAllPaymentAccount operation.
     * @callback module:api/EwalletApi~ewalletControllerListAllPaymentAccountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListPaymentAccountResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * ListAllPaymentAccount &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/EwalletApi~ewalletControllerListAllPaymentAccountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListPaymentAccountResponse}
     */
    this.ewalletControllerListAllPaymentAccount = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListPaymentAccountResponse;

      return this.apiClient.callApi(
        '/ewallet/full-linked-payment-account', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerPostBOTopUpRequest operation.
     * @callback module:api/EwalletApi~ewalletControllerPostBOTopUpRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterBOTopUpResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PostBOTopUpRequest &lt;br&gt;
     * @param {module:model/PresenterBOTopUpRequest} body body for Ewallet content
     * @param {module:api/EwalletApi~ewalletControllerPostBOTopUpRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterBOTopUpResponse}
     */
    this.ewalletControllerPostBOTopUpRequest = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling ewalletControllerPostBOTopUpRequest");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PresenterBOTopUpResponse;

      return this.apiClient.callApi(
        '/ewallet/bo-topup', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerPostCreateLoanConfirm operation.
     * @callback module:api/EwalletApi~ewalletControllerPostCreateLoanConfirmCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterLoanConfirmResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PostCreateLoanConfirm &lt;br&gt;
     * @param {module:model/PresenterLoanConfirmRequest} body body for Loan confirm
     * @param {module:api/EwalletApi~ewalletControllerPostCreateLoanConfirmCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterLoanConfirmResponse}
     */
    this.ewalletControllerPostCreateLoanConfirm = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling ewalletControllerPostCreateLoanConfirm");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PresenterLoanConfirmResponse;

      return this.apiClient.callApi(
        '/ewallet/create-loan-confirm', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerPostCreateLoanRequest operation.
     * @callback module:api/EwalletApi~ewalletControllerPostCreateLoanRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterLoanRequestResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PostCreateLoanRequest &lt;br&gt;
     * @param {module:model/PresenterLoanRequestRequest} body body for Loan request
     * @param {module:api/EwalletApi~ewalletControllerPostCreateLoanRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterLoanRequestResponse}
     */
    this.ewalletControllerPostCreateLoanRequest = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling ewalletControllerPostCreateLoanRequest");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PresenterLoanRequestResponse;

      return this.apiClient.callApi(
        '/ewallet/create-loan-request', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerPostLinkResourceConfirm operation.
     * @callback module:api/EwalletApi~ewalletControllerPostLinkResourceConfirmCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterLinkResourceConfirmResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PostPreCloseConfirm &lt;br&gt;
     * @param {module:model/PresenterLinkResourceConfirmRequest} body body for Pre close confirm
     * @param {module:api/EwalletApi~ewalletControllerPostLinkResourceConfirmCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterLinkResourceConfirmResponse}
     */
    this.ewalletControllerPostLinkResourceConfirm = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling ewalletControllerPostLinkResourceConfirm");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PresenterLinkResourceConfirmResponse;

      return this.apiClient.callApi(
        '/ewallet/link-resource-confirm', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerPostPreCloseConfirm operation.
     * @callback module:api/EwalletApi~ewalletControllerPostPreCloseConfirmCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterPreCloseConfirmResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PostPreCloseConfirm &lt;br&gt;
     * @param {module:model/PresenterPreCloseConfirmRequest} body body for Pre close confirm
     * @param {module:api/EwalletApi~ewalletControllerPostPreCloseConfirmCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterPreCloseConfirmResponse}
     */
    this.ewalletControllerPostPreCloseConfirm = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling ewalletControllerPostPreCloseConfirm");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PresenterPreCloseConfirmResponse;

      return this.apiClient.callApi(
        '/ewallet/pre-close-confirm', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerPostTopUpConfirm operation.
     * @callback module:api/EwalletApi~ewalletControllerPostTopUpConfirmCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterTopUpConfirmResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PostTopUpConfirm &lt;br&gt;
     * @param {module:model/PresenterTopUpConfirmRequest} body body for Ewallet content
     * @param {module:api/EwalletApi~ewalletControllerPostTopUpConfirmCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterTopUpConfirmResponse}
     */
    this.ewalletControllerPostTopUpConfirm = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling ewalletControllerPostTopUpConfirm");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PresenterTopUpConfirmResponse;

      return this.apiClient.callApi(
        '/ewallet/topup-confirm', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerPostTopUpConfirm_0 operation.
     * @callback module:api/EwalletApi~ewalletControllerPostTopUpConfirm_0Callback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterTopUpRequestResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PostPaymentConfirm &lt;br&gt;
     * @param {module:model/PresenterTopUpRequest} body body for Ewallet content
     * @param {module:api/EwalletApi~ewalletControllerPostTopUpConfirm_0Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterTopUpRequestResponse}
     */
    this.ewalletControllerPostTopUpConfirm_0 = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling ewalletControllerPostTopUpConfirm_0");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PresenterTopUpRequestResponse;

      return this.apiClient.callApi(
        '/ewallet/topup-request', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerPostUnlinkResource operation.
     * @callback module:api/EwalletApi~ewalletControllerPostUnlinkResourceCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterUnlinkResourceResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PostUnlinkResource &lt;br&gt;
     * @param {module:model/PresenterUnlinkResourceRequest} body body for Ewallet content
     * @param {module:api/EwalletApi~ewalletControllerPostUnlinkResourceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterUnlinkResourceResponse}
     */
    this.ewalletControllerPostUnlinkResource = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling ewalletControllerPostUnlinkResource");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = PresenterUnlinkResourceResponse;

      return this.apiClient.callApi(
        '/ewallet/unlink-resource', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ewalletControllerUnlinkPaymentAccount operation.
     * @callback module:api/EwalletApi~ewalletControllerUnlinkPaymentAccountCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * UnlinkPaymentAccount &lt;br&gt;
     * @param {module:model/PresenterUnlinkPaymentAccountReq} body body for Pre close confirm
     * @param {module:api/EwalletApi~ewalletControllerUnlinkPaymentAccountCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.ewalletControllerUnlinkPaymentAccount = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling ewalletControllerUnlinkPaymentAccount");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/ewallet/unlink-payment-account', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
