/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterCommonErrResponse', 'model/PresenterListNotiScheduler', 'model/PresenterListNotiSschedulerResponse', 'model/PresenterNotiScheduler', 'model/PresenterNotiSchedulerRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PresenterCommonErrResponse'), require('../model/PresenterListNotiScheduler'), require('../model/PresenterListNotiSschedulerResponse'), require('../model/PresenterNotiScheduler'), require('../model/PresenterNotiSchedulerRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.NotischedulersApi = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterCommonErrResponse, root.NeomedApi.PresenterListNotiScheduler, root.NeomedApi.PresenterListNotiSschedulerResponse, root.NeomedApi.PresenterNotiScheduler, root.NeomedApi.PresenterNotiSchedulerRequest);
  }
}(this, function(ApiClient, PresenterCommonErrResponse, PresenterListNotiScheduler, PresenterListNotiSschedulerResponse, PresenterNotiScheduler, PresenterNotiSchedulerRequest) {
  'use strict';

  /**
   * Notischedulers service.
   * @module api/NotischedulersApi
   * @version 1.0.0
   */

  /**
   * Constructs a new NotischedulersApi. 
   * @alias module:api/NotischedulersApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the notiSchedulerControllerDelete operation.
     * @callback module:api/NotischedulersApi~notiSchedulerControllerDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete the NotiScheduler &lt;br&gt;
     * @param {String} id The id you want to delete
     * @param {module:api/NotischedulersApi~notiSchedulerControllerDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.notiSchedulerControllerDelete = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling notiSchedulerControllerDelete");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/noti-schedulers/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the notiSchedulerControllerGetAll operation.
     * @callback module:api/NotischedulersApi~notiSchedulerControllerGetAllCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListNotiSschedulerResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get list voucher &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {Number} opts.campaignId campaignId
     * @param {Number} opts.status status
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/NotischedulersApi~notiSchedulerControllerGetAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListNotiSschedulerResponse}
     */
    this.notiSchedulerControllerGetAll = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'campaignId': opts['campaignId'],
        'status': opts['status'],
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListNotiSschedulerResponse;

      return this.apiClient.callApi(
        '/noti-schedulers/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the notiSchedulerControllerGetOne operation.
     * @callback module:api/NotischedulersApi~notiSchedulerControllerGetOneCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterNotiScheduler} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get notischeduler by id &lt;br&gt;
     * @param {String} notiSchedulerId notiSchedulerId
     * @param {module:api/NotischedulersApi~notiSchedulerControllerGetOneCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterNotiScheduler}
     */
    this.notiSchedulerControllerGetOne = function(notiSchedulerId, callback) {
      var postBody = null;

      // verify the required parameter 'notiSchedulerId' is set
      if (notiSchedulerId === undefined || notiSchedulerId === null) {
        throw new Error("Missing the required parameter 'notiSchedulerId' when calling notiSchedulerControllerGetOne");
      }


      var pathParams = {
        'notiSchedulerId': notiSchedulerId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterNotiScheduler;

      return this.apiClient.callApi(
        '/noti-schedulers/{notiSchedulerId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the notiSchedulerControllerPost operation.
     * @callback module:api/NotischedulersApi~notiSchedulerControllerPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create Voucher &lt;br&gt;
     * @param {module:model/PresenterListNotiScheduler} body body for NotiScheduler , format Exect_time : dd/MM/yyyy hh:mm:ss
     * @param {module:api/NotischedulersApi~notiSchedulerControllerPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.notiSchedulerControllerPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling notiSchedulerControllerPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/noti-schedulers/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the notiSchedulerControllerPut operation.
     * @callback module:api/NotischedulersApi~notiSchedulerControllerPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCommonErrResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update the NotiScheduler &lt;br&gt;
     * @param {String} id The id you want to update
     * @param {module:model/PresenterNotiSchedulerRequest} body body for NotiScheduler, format Exect_time : dd/MM/yyyy hh:mm:ss
     * @param {module:api/NotischedulersApi~notiSchedulerControllerPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCommonErrResponse}
     */
    this.notiSchedulerControllerPut = function(id, body, callback) {
      var postBody = body;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling notiSchedulerControllerPut");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling notiSchedulerControllerPut");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCommonErrResponse;

      return this.apiClient.callApi(
        '/noti-schedulers/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
