/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterAddOrderInvoiceResponse', 'model/PresenterBuyAgainResponse', 'model/PresenterCancelOrderRequest', 'model/PresenterCancelOrderResponse', 'model/PresenterChangeOrderStatus', 'model/PresenterCountOrdersByStatusResponse', 'model/PresenterDistributorCreateMultiOrdersRequest', 'model/PresenterDistributorCreateMultiOrdersResponse', 'model/PresenterGetListOrderResponse', 'model/PresenterGetOneOrderResponse', 'model/PresenterGetOrderItemChangeHistoryResponse', 'model/PresenterGetStateHistoryResponse', 'model/PresenterInvoiceInfo', 'model/PresenterListOrdersBackOfficeResponse', 'model/PresenterListingStatusResponse', 'model/PresenterManualTopUpAccumulatedResponse', 'model/PresenterPayOrderResponse', 'model/PresenterPayOrdersRequest', 'model/PresenterPaymentConfirmRequest', 'model/PresenterPaymentConfirmResponseV2', 'model/PresenterPaymentRequestBizRequest', 'model/PresenterPaymentRequestBizResponse', 'model/PresenterPaymentRequestRequest', 'model/PresenterPaymentRequestResponseV2', 'model/PresenterUpdateOrderItemRequest', 'model/PresenterUpdateOrderItemResponse', 'model/PresenterUpdateOrderRequest', 'model/PresenterUpdateOrderResponse', 'model/PresenterUpdateStatusResponse', 'model/PresenterUserConfirmedResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PresenterAddOrderInvoiceResponse'), require('../model/PresenterBuyAgainResponse'), require('../model/PresenterCancelOrderRequest'), require('../model/PresenterCancelOrderResponse'), require('../model/PresenterChangeOrderStatus'), require('../model/PresenterCountOrdersByStatusResponse'), require('../model/PresenterDistributorCreateMultiOrdersRequest'), require('../model/PresenterDistributorCreateMultiOrdersResponse'), require('../model/PresenterGetListOrderResponse'), require('../model/PresenterGetOneOrderResponse'), require('../model/PresenterGetOrderItemChangeHistoryResponse'), require('../model/PresenterGetStateHistoryResponse'), require('../model/PresenterInvoiceInfo'), require('../model/PresenterListOrdersBackOfficeResponse'), require('../model/PresenterListingStatusResponse'), require('../model/PresenterManualTopUpAccumulatedResponse'), require('../model/PresenterPayOrderResponse'), require('../model/PresenterPayOrdersRequest'), require('../model/PresenterPaymentConfirmRequest'), require('../model/PresenterPaymentConfirmResponseV2'), require('../model/PresenterPaymentRequestBizRequest'), require('../model/PresenterPaymentRequestBizResponse'), require('../model/PresenterPaymentRequestRequest'), require('../model/PresenterPaymentRequestResponseV2'), require('../model/PresenterUpdateOrderItemRequest'), require('../model/PresenterUpdateOrderItemResponse'), require('../model/PresenterUpdateOrderRequest'), require('../model/PresenterUpdateOrderResponse'), require('../model/PresenterUpdateStatusResponse'), require('../model/PresenterUserConfirmedResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.OrdersApi = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterAddOrderInvoiceResponse, root.NeomedApi.PresenterBuyAgainResponse, root.NeomedApi.PresenterCancelOrderRequest, root.NeomedApi.PresenterCancelOrderResponse, root.NeomedApi.PresenterChangeOrderStatus, root.NeomedApi.PresenterCountOrdersByStatusResponse, root.NeomedApi.PresenterDistributorCreateMultiOrdersRequest, root.NeomedApi.PresenterDistributorCreateMultiOrdersResponse, root.NeomedApi.PresenterGetListOrderResponse, root.NeomedApi.PresenterGetOneOrderResponse, root.NeomedApi.PresenterGetOrderItemChangeHistoryResponse, root.NeomedApi.PresenterGetStateHistoryResponse, root.NeomedApi.PresenterInvoiceInfo, root.NeomedApi.PresenterListOrdersBackOfficeResponse, root.NeomedApi.PresenterListingStatusResponse, root.NeomedApi.PresenterManualTopUpAccumulatedResponse, root.NeomedApi.PresenterPayOrderResponse, root.NeomedApi.PresenterPayOrdersRequest, root.NeomedApi.PresenterPaymentConfirmRequest, root.NeomedApi.PresenterPaymentConfirmResponseV2, root.NeomedApi.PresenterPaymentRequestBizRequest, root.NeomedApi.PresenterPaymentRequestBizResponse, root.NeomedApi.PresenterPaymentRequestRequest, root.NeomedApi.PresenterPaymentRequestResponseV2, root.NeomedApi.PresenterUpdateOrderItemRequest, root.NeomedApi.PresenterUpdateOrderItemResponse, root.NeomedApi.PresenterUpdateOrderRequest, root.NeomedApi.PresenterUpdateOrderResponse, root.NeomedApi.PresenterUpdateStatusResponse, root.NeomedApi.PresenterUserConfirmedResponse);
  }
}(this, function(ApiClient, PresenterAddOrderInvoiceResponse, PresenterBuyAgainResponse, PresenterCancelOrderRequest, PresenterCancelOrderResponse, PresenterChangeOrderStatus, PresenterCountOrdersByStatusResponse, PresenterDistributorCreateMultiOrdersRequest, PresenterDistributorCreateMultiOrdersResponse, PresenterGetListOrderResponse, PresenterGetOneOrderResponse, PresenterGetOrderItemChangeHistoryResponse, PresenterGetStateHistoryResponse, PresenterInvoiceInfo, PresenterListOrdersBackOfficeResponse, PresenterListingStatusResponse, PresenterManualTopUpAccumulatedResponse, PresenterPayOrderResponse, PresenterPayOrdersRequest, PresenterPaymentConfirmRequest, PresenterPaymentConfirmResponseV2, PresenterPaymentRequestBizRequest, PresenterPaymentRequestBizResponse, PresenterPaymentRequestRequest, PresenterPaymentRequestResponseV2, PresenterUpdateOrderItemRequest, PresenterUpdateOrderItemResponse, PresenterUpdateOrderRequest, PresenterUpdateOrderResponse, PresenterUpdateStatusResponse, PresenterUserConfirmedResponse) {
  'use strict';

  /**
   * Orders service.
   * @module api/OrdersApi
   * @version 1.0.0
   */

  /**
   * Constructs a new OrdersApi. 
   * @alias module:api/OrdersApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the orderControllerAddInvoice operation.
     * @callback module:api/OrdersApi~orderControllerAddInvoiceCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterAddOrderInvoiceResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * add user&#39;s invoice &lt;br&gt;
     * @param {module:model/PresenterInvoiceInfo} body content body
     * @param {Object} opts Optional parameters
     * @param {String} opts.orderId order id
     * @param {Number} opts.scope invoice for personal (1 - default) or business (2)
     * @param {module:api/OrdersApi~orderControllerAddInvoiceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterAddOrderInvoiceResponse}
     */
    this.orderControllerAddInvoice = function(body, opts, callback) {
      opts = opts || {};
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderControllerAddInvoice");
      }


      var pathParams = {
      };
      var queryParams = {
        'orderId': opts['orderId'],
        'scope': opts['scope']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterAddOrderInvoiceResponse;

      return this.apiClient.callApi(
        '/orders/invoice', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerBuyAgain operation.
     * @callback module:api/OrdersApi~orderControllerBuyAgainCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterBuyAgainResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * buy again with exist order &lt;br&gt;
     * @param {String} orderId order id
     * @param {module:api/OrdersApi~orderControllerBuyAgainCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterBuyAgainResponse}
     */
    this.orderControllerBuyAgain = function(orderId, callback) {
      var postBody = null;

      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling orderControllerBuyAgain");
      }


      var pathParams = {
        'orderId': orderId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterBuyAgainResponse;

      return this.apiClient.callApi(
        '/orders/buy_again/{orderId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerCancelOrder operation.
     * @callback module:api/OrdersApi~orderControllerCancelOrderCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCancelOrderResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * cancel exist order &lt;br&gt;
     * @param {module:model/PresenterCancelOrderRequest} body body for request content
     * @param {module:api/OrdersApi~orderControllerCancelOrderCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCancelOrderResponse}
     */
    this.orderControllerCancelOrder = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderControllerCancelOrder");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCancelOrderResponse;

      return this.apiClient.callApi(
        '/orders/cancel', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerChangeOrderStatus operation.
     * @callback module:api/OrdersApi~orderControllerChangeOrderStatusCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * pay order transaction &lt;br&gt;
     * @param {module:model/PresenterChangeOrderStatus} body body for request content
     * @param {module:api/OrdersApi~orderControllerChangeOrderStatusCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.orderControllerChangeOrderStatus = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderControllerChangeOrderStatus");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/orders/back-offices/change-status/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerCountOrdersByStatus operation.
     * @callback module:api/OrdersApi~orderControllerCountOrdersByStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCountOrdersByStatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * aggregation with countype (distributor,...) and status order &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {Number} opts.ctype type of counting: 0 - distributor (default)
     * @param {String} opts.status a string order&#39;s status was separated by commas (example: status&#x3D;1,2,3)
     * @param {String} opts.subStatus a string fulfillment status was separated by commas (example: status&#x3D;1,2,3)
     * @param {String} opts.fromAt begin time to count (format time: dd-MM-yyyy)
     * @param {String} opts.toAt end time to count (format time: dd-MM-yyyy)
     * @param {module:api/OrdersApi~orderControllerCountOrdersByStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCountOrdersByStatusResponse}
     */
    this.orderControllerCountOrdersByStatus = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'ctype': opts['ctype'],
        'status': opts['status'],
        'subStatus': opts['subStatus'],
        'fromAt': opts['fromAt'],
        'toAt': opts['toAt']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCountOrdersByStatusResponse;

      return this.apiClient.callApi(
        '/orders/back-offices/counting-orders', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerDistributorCreateMultiOrders operation.
     * @callback module:api/OrdersApi~orderControllerDistributorCreateMultiOrdersCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterDistributorCreateMultiOrdersResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create multi order from operator&#39;s distributor for customer &lt;br&gt;
     * @param {module:model/PresenterDistributorCreateMultiOrdersRequest} body body for request content
     * @param {module:api/OrdersApi~orderControllerDistributorCreateMultiOrdersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterDistributorCreateMultiOrdersResponse}
     */
    this.orderControllerDistributorCreateMultiOrders = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderControllerDistributorCreateMultiOrders");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterDistributorCreateMultiOrdersResponse;

      return this.apiClient.callApi(
        '/orders/distributors/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerGetAll operation.
     * @callback module:api/OrdersApi~orderControllerGetAllCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterGetListOrderResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Orders &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {Number} opts.size Limit the size of result set. Must be an integer
     * @param {String} opts.next next cursor
     * @param {Number} opts.status order status (if negative value, it&#39;s mean exclude). Array status will use comma separated(example: 1,2))
     * @param {Number} opts.paymentStatus payment status (if negative value, it&#39;s mean exclude. Array status will use comma separated(example: 1,2))
     * @param {String} opts.pmc payment method code (cod)
     * @param {module:api/OrdersApi~orderControllerGetAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterGetListOrderResponse}
     */
    this.orderControllerGetAll = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'size': opts['size'],
        'next': opts['next'],
        'status': opts['status'],
        'paymentStatus': opts['paymentStatus'],
        'pmc': opts['pmc']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterGetListOrderResponse;

      return this.apiClient.callApi(
        '/orders/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerGetAllBackOffice operation.
     * @callback module:api/OrdersApi~orderControllerGetAllBackOfficeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListOrdersBackOfficeResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Orders &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {Number} opts.size Limit the size of result set. Must be an integer (default &#x3D; 50)
     * @param {Number} opts.page Offset of result
     * @param {Number} opts.status Order status
     * @param {Number} opts.subStatus Fulfillment status
     * @param {Number} opts.distributorId distributor id
     * @param {String} opts.fromAt begin time to statistics (format time: dd-MM-yyyy)
     * @param {String} opts.toAt end time to statistics (format time: dd-MM-yyyy)
     * @param {module:api/OrdersApi~orderControllerGetAllBackOfficeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListOrdersBackOfficeResponse}
     */
    this.orderControllerGetAllBackOffice = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'size': opts['size'],
        'page': opts['page'],
        'status': opts['status'],
        'subStatus': opts['subStatus'],
        'distributorId': opts['distributorId'],
        'fromAt': opts['fromAt'],
        'toAt': opts['toAt']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListOrdersBackOfficeResponse;

      return this.apiClient.callApi(
        '/orders/back-offices', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerGetItemsChangedHistory operation.
     * @callback module:api/OrdersApi~orderControllerGetItemsChangedHistoryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterGetOrderItemChangeHistoryResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get order items changed history &lt;br&gt;
     * @param {String} orderId order id
     * @param {Object} opts Optional parameters
     * @param {String} opts.cursor next cursor
     * @param {Boolean} opts.latest only get latest changed item
     * @param {Boolean} opts.isConfirmed only state confirmed
     * @param {module:api/OrdersApi~orderControllerGetItemsChangedHistoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterGetOrderItemChangeHistoryResponse}
     */
    this.orderControllerGetItemsChangedHistory = function(orderId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling orderControllerGetItemsChangedHistory");
      }


      var pathParams = {
        'orderId': orderId
      };
      var queryParams = {
        'cursor': opts['cursor'],
        'latest': opts['latest'],
        'isConfirmed': opts['isConfirmed']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterGetOrderItemChangeHistoryResponse;

      return this.apiClient.callApi(
        '/orders/items/history/{orderId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerGetOne operation.
     * @callback module:api/OrdersApi~orderControllerGetOneCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterGetOneOrderResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Order by id &lt;br&gt;
     * @param {String} id order id
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.backOffice from back-office or normal user
     * @param {module:api/OrdersApi~orderControllerGetOneCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterGetOneOrderResponse}
     */
    this.orderControllerGetOne = function(id, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling orderControllerGetOne");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
        'backOffice': opts['backOffice']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterGetOneOrderResponse;

      return this.apiClient.callApi(
        '/orders/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerGetStateHistory operation.
     * @callback module:api/OrdersApi~orderControllerGetStateHistoryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterGetStateHistoryResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Order by id &lt;br&gt;
     * @param {String} orderId order id
     * @param {module:api/OrdersApi~orderControllerGetStateHistoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterGetStateHistoryResponse}
     */
    this.orderControllerGetStateHistory = function(orderId, callback) {
      var postBody = null;

      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling orderControllerGetStateHistory");
      }


      var pathParams = {
        'orderId': orderId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterGetStateHistoryResponse;

      return this.apiClient.callApi(
        '/orders/state-histories/{orderId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerListingStatus operation.
     * @callback module:api/OrdersApi~orderControllerListingStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListingStatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * aggregation by status (order or payment) &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {Number} opts.ts type of status: 0 - order (default), 1 - payment
     * @param {String} opts.fromAt begin time to count (format time: dd-MM-yyyy)
     * @param {String} opts.toAt end time to count (format time: dd-MM-yyyy)
     * @param {module:api/OrdersApi~orderControllerListingStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListingStatusResponse}
     */
    this.orderControllerListingStatus = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'ts': opts['ts'],
        'fromAt': opts['fromAt'],
        'toAt': opts['toAt']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListingStatusResponse;

      return this.apiClient.callApi(
        '/orders/back-offices/listing-status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerManualTopUpAccumulated operation.
     * @callback module:api/OrdersApi~orderControllerManualTopUpAccumulatedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterManualTopUpAccumulatedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * manual topup accumulated &lt;br&gt;
     * @param {String} orderId order id
     * @param {String} orderUid id user own order
     * @param {module:api/OrdersApi~orderControllerManualTopUpAccumulatedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterManualTopUpAccumulatedResponse}
     */
    this.orderControllerManualTopUpAccumulated = function(orderId, orderUid, callback) {
      var postBody = null;

      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling orderControllerManualTopUpAccumulated");
      }

      // verify the required parameter 'orderUid' is set
      if (orderUid === undefined || orderUid === null) {
        throw new Error("Missing the required parameter 'orderUid' when calling orderControllerManualTopUpAccumulated");
      }


      var pathParams = {
      };
      var queryParams = {
        'orderId': orderId,
        'orderUid': orderUid
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterManualTopUpAccumulatedResponse;

      return this.apiClient.callApi(
        '/orders/manual-topup-accum', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerMigrateToElastic operation.
     * @callback module:api/OrdersApi~orderControllerMigrateToElasticCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * migrate all orders into elastic &lt;br&gt;
     * @param {String} checksum checksum to validate
     * @param {Object} opts Optional parameters
     * @param {String} opts.fromAt from At: dd-MM-yyyy
     * @param {String} opts.toAt to At: dd-MM-yyyy
     * @param {String} opts.orderIds orderids sepparate by commas
     * @param {module:api/OrdersApi~orderControllerMigrateToElasticCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.orderControllerMigrateToElastic = function(checksum, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'checksum' is set
      if (checksum === undefined || checksum === null) {
        throw new Error("Missing the required parameter 'checksum' when calling orderControllerMigrateToElastic");
      }


      var pathParams = {
      };
      var queryParams = {
        'checksum': checksum,
        'fromAt': opts['fromAt'],
        'toAt': opts['toAt'],
        'orderIds': opts['orderIds']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/orders/back-offices/migrate-elastic', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerPayment operation.
     * @callback module:api/OrdersApi~orderControllerPaymentCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterPayOrderResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * pay order transaction &lt;br&gt;
     * @param {String} orderId order id
     * @param {String} pmCode payment method cod
     * @param {module:api/OrdersApi~orderControllerPaymentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterPayOrderResponse}
     */
    this.orderControllerPayment = function(orderId, pmCode, callback) {
      var postBody = null;

      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling orderControllerPayment");
      }

      // verify the required parameter 'pmCode' is set
      if (pmCode === undefined || pmCode === null) {
        throw new Error("Missing the required parameter 'pmCode' when calling orderControllerPayment");
      }


      var pathParams = {
        'orderId': orderId,
        'pmCode': pmCode
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterPayOrderResponse;

      return this.apiClient.callApi(
        '/orders/payment/{orderId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerPaymentConfirm operation.
     * @callback module:api/OrdersApi~orderControllerPaymentConfirmCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterPaymentConfirmResponseV2} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PaymentConfirm &lt;br&gt;
     * @param {module:model/PresenterPaymentConfirmRequest} body body for Ewallet content
     * @param {module:api/OrdersApi~orderControllerPaymentConfirmCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterPaymentConfirmResponseV2}
     */
    this.orderControllerPaymentConfirm = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderControllerPaymentConfirm");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterPaymentConfirmResponseV2;

      return this.apiClient.callApi(
        '/orders/payment-confirm', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerPaymentRequest operation.
     * @callback module:api/OrdersApi~orderControllerPaymentRequestCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterPaymentRequestResponseV2} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PaymentRequest &lt;br&gt;
     * @param {module:model/PresenterPaymentRequestRequest} body body for request content
     * @param {module:api/OrdersApi~orderControllerPaymentRequestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterPaymentRequestResponseV2}
     */
    this.orderControllerPaymentRequest = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderControllerPaymentRequest");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterPaymentRequestResponseV2;

      return this.apiClient.callApi(
        '/orders/payment-request', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerPaymentRequestBiz operation.
     * @callback module:api/OrdersApi~orderControllerPaymentRequestBizCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterPaymentRequestBizResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PaymentRequestBiz &lt;br&gt;
     * @param {module:model/PresenterPaymentRequestBizRequest} body body for request content
     * @param {module:api/OrdersApi~orderControllerPaymentRequestBizCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterPaymentRequestBizResponse}
     */
    this.orderControllerPaymentRequestBiz = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderControllerPaymentRequestBiz");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterPaymentRequestBizResponse;

      return this.apiClient.callApi(
        '/orders/payment-request-biz', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerPayments operation.
     * @callback module:api/OrdersApi~orderControllerPaymentsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterPayOrderResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * pay order transaction &lt;br&gt;
     * @param {module:model/PresenterPayOrdersRequest} body listing orders pay
     * @param {module:api/OrdersApi~orderControllerPaymentsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterPayOrderResponse}
     */
    this.orderControllerPayments = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderControllerPayments");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterPayOrderResponse;

      return this.apiClient.callApi(
        '/orders/payments', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerQueryNextStatus operation.
     * @callback module:api/OrdersApi~orderControllerQueryNextStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterGetStateHistoryResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * query next fulfillment status &lt;br&gt;
     * @param {String} orderId order id
     * @param {module:api/OrdersApi~orderControllerQueryNextStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterGetStateHistoryResponse}
     */
    this.orderControllerQueryNextStatus = function(orderId, callback) {
      var postBody = null;

      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling orderControllerQueryNextStatus");
      }


      var pathParams = {
        'orderId': orderId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterGetStateHistoryResponse;

      return this.apiClient.callApi(
        '/orders/back-offices/status/{orderId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerUpdateOrder operation.
     * @callback module:api/OrdersApi~orderControllerUpdateOrderCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterUpdateOrderResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update order &lt;br&gt;
     * @param {String} orderId order id
     * @param {module:model/PresenterUpdateOrderRequest} body content body
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.backOffice whether is backoffice account
     * @param {module:api/OrdersApi~orderControllerUpdateOrderCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterUpdateOrderResponse}
     */
    this.orderControllerUpdateOrder = function(orderId, body, opts, callback) {
      opts = opts || {};
      var postBody = body;

      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling orderControllerUpdateOrder");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderControllerUpdateOrder");
      }


      var pathParams = {
        'orderId': orderId
      };
      var queryParams = {
        'backOffice': opts['backOffice']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterUpdateOrderResponse;

      return this.apiClient.callApi(
        '/orders/{orderId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerUpdateOrderItem operation.
     * @callback module:api/OrdersApi~orderControllerUpdateOrderItemCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterUpdateOrderItemResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update order item &lt;br&gt;
     * @param {String} orderId order id
     * @param {module:model/PresenterUpdateOrderItemRequest} body content body
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.backOffice whether is backoffice account
     * @param {module:api/OrdersApi~orderControllerUpdateOrderItemCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterUpdateOrderItemResponse}
     */
    this.orderControllerUpdateOrderItem = function(orderId, body, opts, callback) {
      opts = opts || {};
      var postBody = body;

      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling orderControllerUpdateOrderItem");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling orderControllerUpdateOrderItem");
      }


      var pathParams = {
        'orderId': orderId
      };
      var queryParams = {
        'backOffice': opts['backOffice']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterUpdateOrderItemResponse;

      return this.apiClient.callApi(
        '/orders/items/{orderId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerUpdateStatus operation.
     * @callback module:api/OrdersApi~orderControllerUpdateStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterUpdateStatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * pay order transaction &lt;br&gt;
     * @param {String} orderId order id
     * @param {Number} newStatus new status updated
     * @param {Object} opts Optional parameters
     * @param {Number} opts.newPaymentStatus new payment status updated
     * @param {Number} opts.paymentAt payment time (unix timestamp)
     * @param {String} opts.extData ext data
     * @param {module:api/OrdersApi~orderControllerUpdateStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterUpdateStatusResponse}
     */
    this.orderControllerUpdateStatus = function(orderId, newStatus, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling orderControllerUpdateStatus");
      }

      // verify the required parameter 'newStatus' is set
      if (newStatus === undefined || newStatus === null) {
        throw new Error("Missing the required parameter 'newStatus' when calling orderControllerUpdateStatus");
      }


      var pathParams = {
        'orderId': orderId
      };
      var queryParams = {
        'newStatus': newStatus,
        'newPaymentStatus': opts['newPaymentStatus'],
        'paymentAt': opts['paymentAt'],
        'extData': opts['extData']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterUpdateStatusResponse;

      return this.apiClient.callApi(
        '/orders/back-offices/status/{orderId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the orderControllerUserConfirmed operation.
     * @callback module:api/OrdersApi~orderControllerUserConfirmedCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterUserConfirmedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * user confirm with changed order by CS &lt;br&gt;
     * @param {String} orderId order id is confirmed
     * @param {module:api/OrdersApi~orderControllerUserConfirmedCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterUserConfirmedResponse}
     */
    this.orderControllerUserConfirmed = function(orderId, callback) {
      var postBody = null;

      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling orderControllerUserConfirmed");
      }


      var pathParams = {
        'orderId': orderId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterUserConfirmedResponse;

      return this.apiClient.callApi(
        '/orders/user-confirm/{orderId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
