/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterAccreditRequest', 'model/PresenterCommonErrResponse', 'model/PresenterCreatePharmacyUpdateRequest', 'model/PresenterListPharmaciesResponse', 'model/PresenterPharmacy', 'model/PresenterPharmacyImports', 'model/PresenterSendMessForPhar', 'model/PresenterUpdatePharmacyRequest', 'model/PresenterUpdatePharmacyStatusRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PresenterAccreditRequest'), require('../model/PresenterCommonErrResponse'), require('../model/PresenterCreatePharmacyUpdateRequest'), require('../model/PresenterListPharmaciesResponse'), require('../model/PresenterPharmacy'), require('../model/PresenterPharmacyImports'), require('../model/PresenterSendMessForPhar'), require('../model/PresenterUpdatePharmacyRequest'), require('../model/PresenterUpdatePharmacyStatusRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PharmaciesApi = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterAccreditRequest, root.NeomedApi.PresenterCommonErrResponse, root.NeomedApi.PresenterCreatePharmacyUpdateRequest, root.NeomedApi.PresenterListPharmaciesResponse, root.NeomedApi.PresenterPharmacy, root.NeomedApi.PresenterPharmacyImports, root.NeomedApi.PresenterSendMessForPhar, root.NeomedApi.PresenterUpdatePharmacyRequest, root.NeomedApi.PresenterUpdatePharmacyStatusRequest);
  }
}(this, function(ApiClient, PresenterAccreditRequest, PresenterCommonErrResponse, PresenterCreatePharmacyUpdateRequest, PresenterListPharmaciesResponse, PresenterPharmacy, PresenterPharmacyImports, PresenterSendMessForPhar, PresenterUpdatePharmacyRequest, PresenterUpdatePharmacyStatusRequest) {
  'use strict';

  /**
   * Pharmacies service.
   * @module api/PharmaciesApi
   * @version 1.0.0
   */

  /**
   * Constructs a new PharmaciesApi. 
   * @alias module:api/PharmaciesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the pharmacityControllerAddOrRemoveAccredit operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerAddOrRemoveAccreditCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add or Remove accredit for pharmacy &lt;br&gt;
     * @param {module:model/PresenterAccreditRequest} body body- type:[1]:Add [2]Remove distributors: a lot of distributor_ids
     * @param {module:api/PharmaciesApi~pharmacityControllerAddOrRemoveAccreditCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.pharmacityControllerAddOrRemoveAccredit = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling pharmacityControllerAddOrRemoveAccredit");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/pharmacies/accredit', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerGetAll operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerGetAllCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListPharmaciesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Pharmacy &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {String} opts.status Status of pharmacy. Must be an string
     * @param {String} opts.fromLastLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.toLastLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.fromApproved format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.toApproved format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.fromFirstLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.toFirstLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/PharmaciesApi~pharmacityControllerGetAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListPharmaciesResponse}
     */
    this.pharmacityControllerGetAll = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'status': opts['status'],
        'from_last_login': opts['fromLastLogin'],
        'to_last_login': opts['toLastLogin'],
        'from_approved': opts['fromApproved'],
        'to_approved': opts['toApproved'],
        'from_first_login': opts['fromFirstLogin'],
        'to_first_login': opts['toFirstLogin'],
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListPharmaciesResponse;

      return this.apiClient.callApi(
        '/pharmacies/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerGetAllAccredit operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerGetAllAccreditCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListPharmaciesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetAllAccredit &lt;br&gt;
     * @param {String} distributorId The distributor_id you want to get pharmacy
     * @param {Boolean} login true:have accredit false: haven&#39;t logged in for the first time.. default:true
     * @param {Object} opts Optional parameters
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/PharmaciesApi~pharmacityControllerGetAllAccreditCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListPharmaciesResponse}
     */
    this.pharmacityControllerGetAllAccredit = function(distributorId, login, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'distributorId' is set
      if (distributorId === undefined || distributorId === null) {
        throw new Error("Missing the required parameter 'distributorId' when calling pharmacityControllerGetAllAccredit");
      }

      // verify the required parameter 'login' is set
      if (login === undefined || login === null) {
        throw new Error("Missing the required parameter 'login' when calling pharmacityControllerGetAllAccredit");
      }


      var pathParams = {
        'distributor_id': distributorId,
        'login': login
      };
      var queryParams = {
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListPharmaciesResponse;

      return this.apiClient.callApi(
        '/pharmacies/accredit/{distributor_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerGetAllInDistributor operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerGetAllInDistributorCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListPharmaciesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetAllInDistributor &lt;br&gt;
     * @param {String} distId The key for static block
     * @param {Object} opts Optional parameters
     * @param {String} opts.status Status of pharmacy. Status &#x3D;&gt; initial approved
     * @param {String} opts.type 0:Phar not in customer group 1:Phar in customer group
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {String} opts.fromLastLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.toLastLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.fromApproved format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.toApproved format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.fromFirstLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.toFirstLogin format yyyy-MM-ddT00:00:00Z
     * @param {module:api/PharmaciesApi~pharmacityControllerGetAllInDistributorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListPharmaciesResponse}
     */
    this.pharmacityControllerGetAllInDistributor = function(distId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'distId' is set
      if (distId === undefined || distId === null) {
        throw new Error("Missing the required parameter 'distId' when calling pharmacityControllerGetAllInDistributor");
      }


      var pathParams = {
        'distId': distId
      };
      var queryParams = {
        'status': opts['status'],
        'type': opts['type'],
        'size': opts['size'],
        'page': opts['page'],
        'from_last_login': opts['fromLastLogin'],
        'to_last_login': opts['toLastLogin'],
        'from_approved': opts['fromApproved'],
        'to_approved': opts['toApproved'],
        'from_first_login': opts['fromFirstLogin'],
        'to_first_login': opts['toFirstLogin']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListPharmaciesResponse;

      return this.apiClient.callApi(
        '/pharmacies/distributors/{distId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerGetAllNotInDistributor operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerGetAllNotInDistributorCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListPharmaciesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetAllNotInDistributor &lt;br&gt;
     * @param {String} distId The key for static block
     * @param {Object} opts Optional parameters
     * @param {String} opts.status Status
     * @param {Number} opts.customerId customerId of pharmacy. Must be an integer
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {String} opts.fromLastLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.toLastLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.fromApproved format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.toApproved format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.fromFirstLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.toFirstLogin format yyyy-MM-ddT00:00:00Z
     * @param {module:api/PharmaciesApi~pharmacityControllerGetAllNotInDistributorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListPharmaciesResponse}
     */
    this.pharmacityControllerGetAllNotInDistributor = function(distId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'distId' is set
      if (distId === undefined || distId === null) {
        throw new Error("Missing the required parameter 'distId' when calling pharmacityControllerGetAllNotInDistributor");
      }


      var pathParams = {
        'distId': distId
      };
      var queryParams = {
        'status': opts['status'],
        'customerId': opts['customerId'],
        'size': opts['size'],
        'page': opts['page'],
        'from_last_login': opts['fromLastLogin'],
        'to_last_login': opts['toLastLogin'],
        'from_approved': opts['fromApproved'],
        'to_approved': opts['toApproved'],
        'from_first_login': opts['fromFirstLogin'],
        'to_first_login': opts['toFirstLogin']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListPharmaciesResponse;

      return this.apiClient.callApi(
        '/pharmacies/distributors/{distId}/non-relation', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerGetByPhone operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerGetByPhoneCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterPharmacy} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Pharmacy by phone number &lt;br&gt;
     * @param {String} phoneNumber The key for static block
     * @param {module:api/PharmaciesApi~pharmacityControllerGetByPhoneCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterPharmacy}
     */
    this.pharmacityControllerGetByPhone = function(phoneNumber, callback) {
      var postBody = null;

      // verify the required parameter 'phoneNumber' is set
      if (phoneNumber === undefined || phoneNumber === null) {
        throw new Error("Missing the required parameter 'phoneNumber' when calling pharmacityControllerGetByPhone");
      }


      var pathParams = {
        'phoneNumber': phoneNumber
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterPharmacy;

      return this.apiClient.callApi(
        '/pharmacies/phone/{phoneNumber}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerGetOne operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerGetOneCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterPharmacy} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Pharmacy by id &lt;br&gt;
     * @param {String} pharId The key for static block
     * @param {module:api/PharmaciesApi~pharmacityControllerGetOneCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterPharmacy}
     */
    this.pharmacityControllerGetOne = function(pharId, callback) {
      var postBody = null;

      // verify the required parameter 'pharId' is set
      if (pharId === undefined || pharId === null) {
        throw new Error("Missing the required parameter 'pharId' when calling pharmacityControllerGetOne");
      }


      var pathParams = {
        'pharId': pharId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterPharmacy;

      return this.apiClient.callApi(
        '/pharmacies/{pharId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerPharmacyImport operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerPharmacyImportCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * add Pharmacy from file import &lt;br&gt;
     * @param {module:model/PresenterPharmacyImports} body body for PharmacyImport content
     * @param {module:api/PharmaciesApi~pharmacityControllerPharmacyImportCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.pharmacityControllerPharmacyImport = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling pharmacityControllerPharmacyImport");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/pharmacies/import', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerPharmacyOnline operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerPharmacyOnlineCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterPharmacy} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Pharmacy online &lt;br&gt;
     * @param {module:api/PharmaciesApi~pharmacityControllerPharmacyOnlineCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterPharmacy}
     */
    this.pharmacityControllerPharmacyOnline = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterPharmacy;

      return this.apiClient.callApi(
        '/pharmacies/online', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerPost operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create Pharmacy &lt;br&gt;
     * @param {module:model/PresenterCreatePharmacyUpdateRequest} body body for Pharmacy content
     * @param {module:api/PharmaciesApi~pharmacityControllerPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.pharmacityControllerPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling pharmacityControllerPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/pharmacies/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerPut operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCommonErrResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update the Pharmacy &lt;br&gt;
     * @param {String} pharId The id you want to update
     * @param {module:model/PresenterCreatePharmacyUpdateRequest} body body for Pharmacy content , format approved_at : dd/MM/yyyy hh:mm:ss
     * @param {module:api/PharmaciesApi~pharmacityControllerPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCommonErrResponse}
     */
    this.pharmacityControllerPut = function(pharId, body, callback) {
      var postBody = body;

      // verify the required parameter 'pharId' is set
      if (pharId === undefined || pharId === null) {
        throw new Error("Missing the required parameter 'pharId' when calling pharmacityControllerPut");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling pharmacityControllerPut");
      }


      var pathParams = {
        'pharId': pharId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCommonErrResponse;

      return this.apiClient.callApi(
        '/pharmacies/{pharId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerSearch operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerSearchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListPharmaciesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get list of Pharmacy by Name or Phone with pagination &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {Number} opts.disId disId
     * @param {String} opts.name name
     * @param {String} opts.fromLastLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.toLastLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.fromApproved format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.toApproved format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.fromFirstLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.toFirstLogin format yyyy-MM-ddT00:00:00Z
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/PharmaciesApi~pharmacityControllerSearchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListPharmaciesResponse}
     */
    this.pharmacityControllerSearch = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'disId': opts['disId'],
        'name': opts['name'],
        'from_last_login': opts['fromLastLogin'],
        'to_last_login': opts['toLastLogin'],
        'from_approved': opts['fromApproved'],
        'to_approved': opts['toApproved'],
        'from_first_login': opts['fromFirstLogin'],
        'to_first_login': opts['toFirstLogin'],
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListPharmaciesResponse;

      return this.apiClient.callApi(
        '/pharmacies/_search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerSendMessForPhar operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerSendMessForPharCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send mess for Phar &lt;br&gt;
     * @param {module:model/PresenterSendMessForPhar} body Ids: customer_group_id or user_id || obj_type: 1.customer_group 2.User || send_type: 1.Now 2.Schedule || exec_time: format dd/MM/yyyy hh:mm:ss
     * @param {module:api/PharmaciesApi~pharmacityControllerSendMessForPharCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.pharmacityControllerSendMessForPhar = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling pharmacityControllerSendMessForPhar");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/pharmacies/noti', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerUpdateFavouriteDis operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerUpdateFavouriteDisCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCommonErrResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update the UpdateFavouriteDis of Pharmacy &lt;br&gt;
     * @param {String} pharId The pharId you want to update
     * @param {String} disId The disId you want to update
     * @param {module:api/PharmaciesApi~pharmacityControllerUpdateFavouriteDisCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCommonErrResponse}
     */
    this.pharmacityControllerUpdateFavouriteDis = function(pharId, disId, callback) {
      var postBody = null;

      // verify the required parameter 'pharId' is set
      if (pharId === undefined || pharId === null) {
        throw new Error("Missing the required parameter 'pharId' when calling pharmacityControllerUpdateFavouriteDis");
      }

      // verify the required parameter 'disId' is set
      if (disId === undefined || disId === null) {
        throw new Error("Missing the required parameter 'disId' when calling pharmacityControllerUpdateFavouriteDis");
      }


      var pathParams = {
        'pharId': pharId,
        'disId': disId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCommonErrResponse;

      return this.apiClient.callApi(
        '/pharmacies/{pharId}/favourite/distributor/{disId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerUpdateSection operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerUpdateSectionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCommonErrResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update section the Pharmacy &lt;br&gt;
     * @param {String} pharId The id you want to update
     * @param {Number} type 0:General Infomation 1:Legal information 2:Billing infomation
     * @param {module:model/PresenterCreatePharmacyUpdateRequest} body body for Pharmacy content
     * @param {module:api/PharmaciesApi~pharmacityControllerUpdateSectionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCommonErrResponse}
     */
    this.pharmacityControllerUpdateSection = function(pharId, type, body, callback) {
      var postBody = body;

      // verify the required parameter 'pharId' is set
      if (pharId === undefined || pharId === null) {
        throw new Error("Missing the required parameter 'pharId' when calling pharmacityControllerUpdateSection");
      }

      // verify the required parameter 'type' is set
      if (type === undefined || type === null) {
        throw new Error("Missing the required parameter 'type' when calling pharmacityControllerUpdateSection");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling pharmacityControllerUpdateSection");
      }


      var pathParams = {
        'pharId': pharId
      };
      var queryParams = {
        'type': type
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCommonErrResponse;

      return this.apiClient.callApi(
        '/pharmacies/{pharId}/section', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerUpdateStatus operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerUpdateStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCommonErrResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update status the Pharmacy &lt;br&gt;
     * @param {String} pharId The id you want to update
     * @param {module:model/PresenterUpdatePharmacyStatusRequest} body body for Pharmacy status
     * @param {module:api/PharmaciesApi~pharmacityControllerUpdateStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCommonErrResponse}
     */
    this.pharmacityControllerUpdateStatus = function(pharId, body, callback) {
      var postBody = body;

      // verify the required parameter 'pharId' is set
      if (pharId === undefined || pharId === null) {
        throw new Error("Missing the required parameter 'pharId' when calling pharmacityControllerUpdateStatus");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling pharmacityControllerUpdateStatus");
      }


      var pathParams = {
        'pharId': pharId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCommonErrResponse;

      return this.apiClient.callApi(
        '/pharmacies/{pharId}/status', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the pharmacityControllerUpdateType operation.
     * @callback module:api/PharmaciesApi~pharmacityControllerUpdateTypeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCommonErrResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update status the Pharmacy &lt;br&gt;
     * @param {String} pharId The id you want to update
     * @param {module:model/PresenterUpdatePharmacyRequest} body body for Pharmacy type
     * @param {module:api/PharmaciesApi~pharmacityControllerUpdateTypeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCommonErrResponse}
     */
    this.pharmacityControllerUpdateType = function(pharId, body, callback) {
      var postBody = body;

      // verify the required parameter 'pharId' is set
      if (pharId === undefined || pharId === null) {
        throw new Error("Missing the required parameter 'pharId' when calling pharmacityControllerUpdateType");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling pharmacityControllerUpdateType");
      }


      var pathParams = {
        'pharId': pharId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCommonErrResponse;

      return this.apiClient.callApi(
        '/pharmacies/{pharId}/type', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
