/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterCommonErrResponse', 'model/PresenterPrice', 'model/PresenterUpdatePriceRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PresenterCommonErrResponse'), require('../model/PresenterPrice'), require('../model/PresenterUpdatePriceRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.PricesApi = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterCommonErrResponse, root.NeomedApi.PresenterPrice, root.NeomedApi.PresenterUpdatePriceRequest);
  }
}(this, function(ApiClient, PresenterCommonErrResponse, PresenterPrice, PresenterUpdatePriceRequest) {
  'use strict';

  /**
   * Prices service.
   * @module api/PricesApi
   * @version 1.0.0
   */

  /**
   * Constructs a new PricesApi. 
   * @alias module:api/PricesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the priceControllerDelete operation.
     * @callback module:api/PricesApi~priceControllerDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCommonErrResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete a price item in the policy &lt;br&gt;
     * @param {String} id The price&#39;s Id
     * @param {module:api/PricesApi~priceControllerDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCommonErrResponse}
     */
    this.priceControllerDelete = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling priceControllerDelete");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCommonErrResponse;

      return this.apiClient.callApi(
        '/prices/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the priceControllerGetPricesByProduct operation.
     * @callback module:api/PricesApi~priceControllerGetPricesByProductCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterPrice} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Options &lt;br&gt;
     * @param {String} productId productId
     * @param {Object} opts Optional parameters
     * @param {String} opts.query Filter. e.g. col1:v1,col2:v2 ...
     * @param {String} opts.fields Fields returned. e.g. col1,col2 ...
     * @param {String} opts.sortby Sorted-by fields. e.g. col1,col2 ...
     * @param {String} opts.order Order corresponding to each sortby field, if single value, apply to all sortby fields. e.g. desc,asc ...
     * @param {String} opts.limit Limit the size of result set. Must be an integer
     * @param {String} opts.offset Start position of result set. Must be an integer
     * @param {module:api/PricesApi~priceControllerGetPricesByProductCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterPrice}
     */
    this.priceControllerGetPricesByProduct = function(productId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'productId' is set
      if (productId === undefined || productId === null) {
        throw new Error("Missing the required parameter 'productId' when calling priceControllerGetPricesByProduct");
      }


      var pathParams = {
        'productId': productId
      };
      var queryParams = {
        'query': opts['query'],
        'fields': opts['fields'],
        'sortby': opts['sortby'],
        'order': opts['order'],
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterPrice;

      return this.apiClient.callApi(
        '/prices/products/{productId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the priceControllerUpdate operation.
     * @callback module:api/PricesApi~priceControllerUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterPrice} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update the Options &lt;br&gt;
     * @param {String} id The id you want to update
     * @param {module:model/PresenterUpdatePriceRequest} body body for Options content
     * @param {module:api/PricesApi~priceControllerUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterPrice}
     */
    this.priceControllerUpdate = function(id, body, callback) {
      var postBody = body;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling priceControllerUpdate");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling priceControllerUpdate");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterPrice;

      return this.apiClient.callApi(
        '/prices/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
