/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterCommonErrResponse', 'model/PresenterListSalesResponse', 'model/PresenterSale'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PresenterCommonErrResponse'), require('../model/PresenterListSalesResponse'), require('../model/PresenterSale'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.SaleApi = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterCommonErrResponse, root.NeomedApi.PresenterListSalesResponse, root.NeomedApi.PresenterSale);
  }
}(this, function(ApiClient, PresenterCommonErrResponse, PresenterListSalesResponse, PresenterSale) {
  'use strict';

  /**
   * Sale service.
   * @module api/SaleApi
   * @version 1.0.0
   */

  /**
   * Constructs a new SaleApi. 
   * @alias module:api/SaleApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the saleControllerGetAll operation.
     * @callback module:api/SaleApi~saleControllerGetAllCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListSalesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Sale &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/SaleApi~saleControllerGetAllCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListSalesResponse}
     */
    this.saleControllerGetAll = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListSalesResponse;

      return this.apiClient.callApi(
        '/sale/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the saleControllerGetAllByDistributor operation.
     * @callback module:api/SaleApi~saleControllerGetAllByDistributorCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListSalesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Sale &lt;br&gt;
     * @param {String} distributorId List sale by DistributorId
     * @param {Object} opts Optional parameters
     * @param {Number} opts.status status
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/SaleApi~saleControllerGetAllByDistributorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListSalesResponse}
     */
    this.saleControllerGetAllByDistributor = function(distributorId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'distributorId' is set
      if (distributorId === undefined || distributorId === null) {
        throw new Error("Missing the required parameter 'distributorId' when calling saleControllerGetAllByDistributor");
      }


      var pathParams = {
        'distributorId': distributorId
      };
      var queryParams = {
        'status': opts['status'],
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListSalesResponse;

      return this.apiClient.callApi(
        '/sale/distributor/{distributorId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the saleControllerGetOne operation.
     * @callback module:api/SaleApi~saleControllerGetOneCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterSale} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Sale by id &lt;br&gt;
     * @param {String} saleId The key for static block
     * @param {module:api/SaleApi~saleControllerGetOneCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterSale}
     */
    this.saleControllerGetOne = function(saleId, callback) {
      var postBody = null;

      // verify the required parameter 'saleId' is set
      if (saleId === undefined || saleId === null) {
        throw new Error("Missing the required parameter 'saleId' when calling saleControllerGetOne");
      }


      var pathParams = {
        'saleId': saleId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterSale;

      return this.apiClient.callApi(
        '/sale/{saleId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the saleControllerPost operation.
     * @callback module:api/SaleApi~saleControllerPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create Sale &lt;br&gt;
     * @param {module:model/PresenterSale} body body for Sale content
     * @param {module:api/SaleApi~saleControllerPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.saleControllerPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling saleControllerPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/sale/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the saleControllerPut operation.
     * @callback module:api/SaleApi~saleControllerPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCommonErrResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update the Sale &lt;br&gt;
     * @param {String} saleId The id you want to update
     * @param {module:api/SaleApi~saleControllerPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCommonErrResponse}
     */
    this.saleControllerPut = function(saleId, callback) {
      var postBody = null;

      // verify the required parameter 'saleId' is set
      if (saleId === undefined || saleId === null) {
        throw new Error("Missing the required parameter 'saleId' when calling saleControllerPut");
      }


      var pathParams = {
        'saleId': saleId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCommonErrResponse;

      return this.apiClient.callApi(
        '/sale/{saleId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the saleControllerPutSale operation.
     * @callback module:api/SaleApi~saleControllerPutSaleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCommonErrResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update the Sale &lt;br&gt;
     * @param {String} saleId The id you want to update
     * @param {module:model/PresenterSale} body body for Pharmacy content
     * @param {module:api/SaleApi~saleControllerPutSaleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCommonErrResponse}
     */
    this.saleControllerPutSale = function(saleId, body, callback) {
      var postBody = body;

      // verify the required parameter 'saleId' is set
      if (saleId === undefined || saleId === null) {
        throw new Error("Missing the required parameter 'saleId' when calling saleControllerPutSale");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling saleControllerPutSale");
      }


      var pathParams = {
        'saleId': saleId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCommonErrResponse;

      return this.apiClient.callApi(
        '/sale/{saleId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the saleControllerSearch operation.
     * @callback module:api/SaleApi~saleControllerSearchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListSalesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get list of Sale by Name or Phone with pagination &lt;br&gt;
     * @param {Object} opts Optional parameters
     * @param {String} opts.disId disId
     * @param {String} opts.name name
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/SaleApi~saleControllerSearchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListSalesResponse}
     */
    this.saleControllerSearch = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'disId': opts['disId'],
        'name': opts['name'],
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListSalesResponse;

      return this.apiClient.callApi(
        '/sale/_search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
