/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterCreateTrademarkAdvertiseRequest', 'model/PresenterListTrademarksResponse', 'model/PresenterTrademark'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PresenterCreateTrademarkAdvertiseRequest'), require('../model/PresenterListTrademarksResponse'), require('../model/PresenterTrademark'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.TrademarksApi = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterCreateTrademarkAdvertiseRequest, root.NeomedApi.PresenterListTrademarksResponse, root.NeomedApi.PresenterTrademark);
  }
}(this, function(ApiClient, PresenterCreateTrademarkAdvertiseRequest, PresenterListTrademarksResponse, PresenterTrademark) {
  'use strict';

  /**
   * Trademarks service.
   * @module api/TrademarksApi
   * @version 1.0.0
   */

  /**
   * Constructs a new TrademarksApi. 
   * @alias module:api/TrademarksApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the trademarkControllerCreate operation.
     * @callback module:api/TrademarksApi~trademarkControllerCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterTrademark} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create Trademark &lt;br&gt;
     * @param {module:model/PresenterTrademark} body body for Trademark content
     * @param {module:api/TrademarksApi~trademarkControllerCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterTrademark}
     */
    this.trademarkControllerCreate = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling trademarkControllerCreate");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterTrademark;

      return this.apiClient.callApi(
        '/trademarks/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the trademarkControllerDelete operation.
     * @callback module:api/TrademarksApi~trademarkControllerDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete the Trademark &lt;br&gt;
     * @param {String} id The id you want to delete
     * @param {module:api/TrademarksApi~trademarkControllerDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.trademarkControllerDelete = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling trademarkControllerDelete");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/trademarks/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the trademarkControllerGetOne operation.
     * @callback module:api/TrademarksApi~trademarkControllerGetOneCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterTrademark} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Trademark by id &lt;br&gt;
     * @param {String} id The key for staticblock
     * @param {module:api/TrademarksApi~trademarkControllerGetOneCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterTrademark}
     */
    this.trademarkControllerGetOne = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling trademarkControllerGetOne");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterTrademark;

      return this.apiClient.callApi(
        '/trademarks/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the trademarkControllerListTrademarkByDistributor operation.
     * @callback module:api/TrademarksApi~trademarkControllerListTrademarkByDistributorCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListTrademarksResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get Trademark &lt;br&gt;
     * @param {String} distributorId distributorId
     * @param {Object} opts Optional parameters
     * @param {String} opts.status Status of result set. Must be an integer
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/TrademarksApi~trademarkControllerListTrademarkByDistributorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListTrademarksResponse}
     */
    this.trademarkControllerListTrademarkByDistributor = function(distributorId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'distributorId' is set
      if (distributorId === undefined || distributorId === null) {
        throw new Error("Missing the required parameter 'distributorId' when calling trademarkControllerListTrademarkByDistributor");
      }


      var pathParams = {
        'distributorId': distributorId
      };
      var queryParams = {
        'status': opts['status'],
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListTrademarksResponse;

      return this.apiClient.callApi(
        '/trademarks/distributors/{distributorId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the trademarkControllerListTrademarkShowHome operation.
     * @callback module:api/TrademarksApi~trademarkControllerListTrademarkShowHomeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterListTrademarksResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get list trademark show home &lt;br&gt;
     * @param {String} distributorId distributorId
     * @param {String} type type (0: NotShowHome , 1: ShowHome)
     * @param {Object} opts Optional parameters
     * @param {String} opts.size Size of result set. Must be an integer
     * @param {String} opts.page Page number of view. Must be an integer
     * @param {module:api/TrademarksApi~trademarkControllerListTrademarkShowHomeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterListTrademarksResponse}
     */
    this.trademarkControllerListTrademarkShowHome = function(distributorId, type, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'distributorId' is set
      if (distributorId === undefined || distributorId === null) {
        throw new Error("Missing the required parameter 'distributorId' when calling trademarkControllerListTrademarkShowHome");
      }

      // verify the required parameter 'type' is set
      if (type === undefined || type === null) {
        throw new Error("Missing the required parameter 'type' when calling trademarkControllerListTrademarkShowHome");
      }


      var pathParams = {
      };
      var queryParams = {
        'distributorId': distributorId,
        'type': type,
        'size': opts['size'],
        'page': opts['page']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterListTrademarksResponse;

      return this.apiClient.callApi(
        '/trademarks/advertisement', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the trademarkControllerUpdate operation.
     * @callback module:api/TrademarksApi~trademarkControllerUpdateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterTrademark} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update the Trademark &lt;br&gt;
     * @param {String} id The id you want to update
     * @param {module:model/PresenterTrademark} body body for Trademark content
     * @param {module:api/TrademarksApi~trademarkControllerUpdateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterTrademark}
     */
    this.trademarkControllerUpdate = function(id, body, callback) {
      var postBody = body;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling trademarkControllerUpdate");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling trademarkControllerUpdate");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterTrademark;

      return this.apiClient.callApi(
        '/trademarks/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the trademarkControllerUpdateAdvertiseTrademark operation.
     * @callback module:api/TrademarksApi~trademarkControllerUpdateAdvertiseTrademarkCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterTrademark} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update advertise trademark &lt;br&gt;
     * @param {module:model/PresenterCreateTrademarkAdvertiseRequest} body body for Trademark(advertise) content
     * @param {module:api/TrademarksApi~trademarkControllerUpdateAdvertiseTrademarkCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterTrademark}
     */
    this.trademarkControllerUpdateAdvertiseTrademark = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling trademarkControllerUpdateAdvertiseTrademark");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterTrademark;

      return this.apiClient.callApi(
        '/trademarks/advertisement', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
