/**
 * Neomed API
 * Neomed API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@ciaolink.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PresenterCommonErrResponse', 'model/PresenterWishlistProductRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PresenterCommonErrResponse'), require('../model/PresenterWishlistProductRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.NeomedApi) {
      root.NeomedApi = {};
    }
    root.NeomedApi.WishlistApi = factory(root.NeomedApi.ApiClient, root.NeomedApi.PresenterCommonErrResponse, root.NeomedApi.PresenterWishlistProductRequest);
  }
}(this, function(ApiClient, PresenterCommonErrResponse, PresenterWishlistProductRequest) {
  'use strict';

  /**
   * Wishlist service.
   * @module api/WishlistApi
   * @version 1.0.0
   */

  /**
   * Constructs a new WishlistApi. 
   * @alias module:api/WishlistApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the wishlistControllerAddWishlistProduct operation.
     * @callback module:api/WishlistApi~wishlistControllerAddWishlistProductCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCommonErrResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * AddWishlistProduct &lt;br&gt;
     * @param {module:model/PresenterWishlistProductRequest} body body for Wishlist content
     * @param {module:api/WishlistApi~wishlistControllerAddWishlistProductCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCommonErrResponse}
     */
    this.wishlistControllerAddWishlistProduct = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling wishlistControllerAddWishlistProduct");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCommonErrResponse;

      return this.apiClient.callApi(
        '/wishlist/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the wishlistControllerRemoveWishlist operation.
     * @callback module:api/WishlistApi~wishlistControllerRemoveWishlistCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PresenterCommonErrResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * RemoveWishlist &lt;br&gt;
     * @param {String} customerId The customerId you want to delete
     * @param {String} productId The productId you want to delete
     * @param {module:api/WishlistApi~wishlistControllerRemoveWishlistCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PresenterCommonErrResponse}
     */
    this.wishlistControllerRemoveWishlist = function(customerId, productId, callback) {
      var postBody = null;

      // verify the required parameter 'customerId' is set
      if (customerId === undefined || customerId === null) {
        throw new Error("Missing the required parameter 'customerId' when calling wishlistControllerRemoveWishlist");
      }

      // verify the required parameter 'productId' is set
      if (productId === undefined || productId === null) {
        throw new Error("Missing the required parameter 'productId' when calling wishlistControllerRemoveWishlist");
      }


      var pathParams = {
      };
      var queryParams = {
        'customerId': customerId,
        'productId': productId
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = PresenterCommonErrResponse;

      return this.apiClient.callApi(
        '/wishlist/', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
