export const getStateStatus = state => state.auth.loginStatus
export const getErrMsg = state => state.auth.errorMsg
export const getAccessToken = state => state.auth.token
export const getAuthStore = state => state.auth
export const getUserId = state => state.auth.userId
export const getRefreshTokenStatus = state => state.auth.refreshTokenStatus
export const getLoginPhoneStatus = state => state.auth.loginPhoneStatus
export const getConfirmLoginStatus = state => state.auth.confirmLoginStatus
export const getConfirmLoginErr = state => state.auth.confirmLoginErr
export const getLoginReqId = state => state.auth.requestId
export const getListByPassFirebase = state => state.auth.listPhoneByPass
export const getStatusGetPhoneByPass = state => state.auth.statusGetPhoneByPass
export const getOtpToken = state => state.auth.otpToken
export const getDeleteAcountStatus = state => state.auth.deleteAcountStatus
export const getDeleteOtpToken = state => state.auth.deleteOtpToken
export const getDeleteAcountId = state => state.auth.deleteAcountId
export const getConfirmDeleteOtpStatus = state => state.auth.confirmDeleteOtpStatus
export const getConfirmDeleteOtpErr =  state => state.auth.confirmDeleteOtpErr
export const getIsLoadNccFavorite = state => state.auth.isLoadNccFavorite