import { StyleSheet } from 'react-native'
import { Fonts } from '~/assets/config'
import Colors from '~/common/Colors/Colors'
import { s, fs } from '~/utils/responsive'
import { brandColors, brandShadow } from '~/design-system/tokens'

export default StyleSheet.create({
  productContainer: {
    backgroundColor: brandColors.surface,
    flexDirection: 'row',
    marginHorizontal: s(16),
    marginBottom: s(10),
    padding: s(12),
    borderRadius: s(22),
    borderWidth: 1,
    borderColor: brandColors.borderSoft,
    ...brandShadow.soft,
  },
  logo: {
    width: s(88),
    height: s(96),
    borderRadius: s(16),
    resizeMode: 'cover',
  },
  logoContainer: {
    width: s(96),
    height: s(104),
    borderRadius: s(18),
    backgroundColor: brandColors.background,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: s(8),
  },
  btnCloseContainer: {
    position: 'absolute',
    right: s(12),
    top: s(12),
    width: s(30),
    height: s(30),
    borderRadius: s(15),
    backgroundColor: brandColors.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnClose: {
    width: s(12),
    height: s(12),
  },
  productInfoContainer: {
    flex: 1,
    paddingVertical: s(2),
    paddingRight: s(28),
    justifyContent: 'space-between',
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: s(10),
    justifyContent: 'space-between',
  },
  paymentPriceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: s(10),
  },
  price: {
    color: brandColors.goldAccent,
    fontSize: fs(14),
    fontWeight: '900',
  },
  
  salePrice: {
    color: brandColors.goldAccent,
    fontSize: fs(14),
    fontWeight: '900',
  },
  discount: {
    color: brandColors.danger,
    fontSize: fs(12),
  },
  quantityBtnContainer: {
    flexDirection: 'row',
    margin: 0, 
    padding: 0,
    height: 34,
    alignItems: 'center', 
    display: 'flex',
    justifyContent: 'center',
    paddingHorizontal: 0,
  },
  quantityBtn: {
    width: 36,
    height: 34,
    padding: 0,
    paddingHorizontal: 0,
    // borderRadius: 36,
    backgroundColor: brandColors.tealLight,
  },
  productQuantity: {
    textAlignVertical: 'center',
    textAlign: 'center',
    fontSize: fs(10),
    color: brandColors.muted,
  },
  productQuantityContainer: {
    borderRadius: 28,
    width: 48,
    textAlignVertical: 'center',
    textAlign: 'center',
    fontSize: fs(10),
    marginHorizontal: 2,
    color: brandColors.muted,
  },
  productName:{
    color: brandColors.textDark,
    fontSize: fs(14),
    fontWeight: '800',
    lineHeight: fs(19),
  },
  inputContainerStyle: {
    display: 'flex',
    justifyContent: 'center',
    padding: 0,
    margin: 0,
    minHeight: 34,
    alignItems: 'center',
  },
  labelStyle: {
    display: 'flex',
    justifyContent: 'center',
    margin: 0,
    fontSize: fs(10),
    lineHeight: fs(10),
    alignItems: 'center',
  },
  comboPromotionContainer: {
    display: 'flex',
    flexDirection: 'row',
    marginTop: s(6),
  },
  originPrice: {
    marginLeft: s(4),
    fontSize: fs(12),
    color: brandColors.mutedLight,
    lineHeight: fs(20),
    textDecorationLine: 'line-through',
  },

  infoContainer: {
    flexDirection: 'row',
    marginTop: s(6),
  },
  priceLabel: {
    flexDirection: 'row',
    fontSize: fs(12),
    fontWeight: '500',
    marginRight: s(6),
    fontFamily: Fonts.meidum,
    color: brandColors.muted,
  },
  promotionLabel: {
    height: s(18),
    width: s(18),
    marginLeft: s(8),
  },
  overlay: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(26, 26, 46, 0.72)',
    borderRadius: s(22),
    position: 'absolute',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
})
