/**
 * neomed accounting API
 * neomed  accounting API documentation
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AddAccountRequestDTO model module.
* @module model/AddAccountRequestDTO
* @version 0.0.2
*/
export default class AddAccountRequestDTO {
    /**
    * Constructs a new <code>AddAccountRequestDTO</code>.
    * @alias module:model/AddAccountRequestDTO
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AddAccountRequestDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AddAccountRequestDTO} obj Optional instance to populate.
    * @return {module:model/AddAccountRequestDTO} The populated <code>AddAccountRequestDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddAccountRequestDTO();
                        
            
            if (data.hasOwnProperty('accountType')) {
                obj['accountType'] = ApiClient.convertToType(data['accountType'], 'String');
            }
            if (data.hasOwnProperty('refId')) {
                obj['refId'] = ApiClient.convertToType(data['refId'], 'Number');
            }
            if (data.hasOwnProperty('refType')) {
                obj['refType'] = ApiClient.convertToType(data['refType'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/AddAccountRequestDTO.AccountTypeEnum} accountType
    */
    'accountType' = undefined;
    /**
    * @member {Number} refId
    */
    'refId' = undefined;
    /**
    * @member {module:model/AddAccountRequestDTO.RefTypeEnum} refType
    */
    'refType' = undefined;



    /**
    * Allowed values for the <code>accountType</code> property.
    * @enum {String}
    * @readonly
    */
    static AccountTypeEnum = {
        /**
         * value: "ASSETS"
         * @const
         */
        "ASSETS": "ASSETS",
        /**
         * value: "PROMOTION"
         * @const
         */
        "PROMOTION": "PROMOTION",
        /**
         * value: "BANK"
         * @const
         */
        "BANK": "BANK"    };
    /**
    * Allowed values for the <code>refType</code> property.
    * @enum {String}
    * @readonly
    */
    static RefTypeEnum = {
        /**
         * value: "DISTRIBUTOR"
         * @const
         */
        "DISTRIBUTOR": "DISTRIBUTOR",
        /**
         * value: "BANK"
         * @const
         */
        "BANK": "BANK"    };

}
