/**
 * neomed accounting API
 * neomed  accounting API documentation
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TopupItemDTO from './TopupItemDTO';

/**
* The TopUpRequestDTO model module.
* @module model/TopUpRequestDTO
* @version 0.0.2
*/
export default class TopUpRequestDTO {
    /**
    * Constructs a new <code>TopUpRequestDTO</code>.
    * @alias module:model/TopUpRequestDTO
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TopUpRequestDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TopUpRequestDTO} obj Optional instance to populate.
    * @return {module:model/TopUpRequestDTO} The populated <code>TopUpRequestDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TopUpRequestDTO();
                        
            
            if (data.hasOwnProperty('topupItems')) {
                obj['topupItems'] = ApiClient.convertToType(data['topupItems'], [TopupItemDTO]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/TopupItemDTO>} topupItems
    */
    'topupItems' = undefined;




}
